#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_IO_Emblem_MultiAttach

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_IO_Emblem_MultiAttach.Apollo_IO_Emblem_MultiAttach_C
// 0x0018 (0x0AE8 - 0x0AD0)
class AApollo_IO_Emblem_MultiAttach_C final : public ABuildingDeco
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AD0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class ABuildingActor*>                 RugAttachmentActors;                               // 0x0AD8(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Apollo_IO_Emblem_MultiAttach(int32 EntryPoint);
	void IReallyDied(class AActor* DamagedActor, float Damage, class AController* InstigatedBy, class AActor* DamageCauser, const struct FVector& HitLocation, class UPrimitiveComponent* FHitComponent, class FName BoneName, const struct FVector& Momentum);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Apollo_IO_Emblem_MultiAttach_C">();
	}
	static class AApollo_IO_Emblem_MultiAttach_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_IO_Emblem_MultiAttach_C>();
	}
};
static_assert(alignof(AApollo_IO_Emblem_MultiAttach_C) == 0x000008, "Wrong alignment on AApollo_IO_Emblem_MultiAttach_C");
static_assert(sizeof(AApollo_IO_Emblem_MultiAttach_C) == 0x000AE8, "Wrong size on AApollo_IO_Emblem_MultiAttach_C");
static_assert(offsetof(AApollo_IO_Emblem_MultiAttach_C, UberGraphFrame) == 0x000AD0, "Member 'AApollo_IO_Emblem_MultiAttach_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AApollo_IO_Emblem_MultiAttach_C, RugAttachmentActors) == 0x000AD8, "Member 'AApollo_IO_Emblem_MultiAttach_C::RugAttachmentActors' has a wrong offset!");

}

