#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_Candle_01_NoLight

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_Candle_01_NoLight.Apollo_Candle_01_NoLight_C
// 0x0050 (0x0BF8 - 0x0BA8)
class AApollo_Candle_01_NoLight_C final : public ABuildingProp
{
public:
	class UStaticMeshComponent*                   BloomPlane5;                                       // 0x0BA8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   BloomPlane4;                                       // 0x0BB0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   BloomPlane3;                                       // 0x0BB8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   BloomPlane2;                                       // 0x0BC0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   BloomPlane1;                                       // 0x0BC8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Flame5;                                            // 0x0BD0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Flame4;                                            // 0x0BD8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Flame3;                                            // 0x0BE0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Flame2;                                            // 0x0BE8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Flame1;                                            // 0x0BF0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Apollo_Candle_01_NoLight_C">();
	}
	static class AApollo_Candle_01_NoLight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_Candle_01_NoLight_C>();
	}
};
static_assert(alignof(AApollo_Candle_01_NoLight_C) == 0x000008, "Wrong alignment on AApollo_Candle_01_NoLight_C");
static_assert(sizeof(AApollo_Candle_01_NoLight_C) == 0x000BF8, "Wrong size on AApollo_Candle_01_NoLight_C");
static_assert(offsetof(AApollo_Candle_01_NoLight_C, BloomPlane5) == 0x000BA8, "Member 'AApollo_Candle_01_NoLight_C::BloomPlane5' has a wrong offset!");
static_assert(offsetof(AApollo_Candle_01_NoLight_C, BloomPlane4) == 0x000BB0, "Member 'AApollo_Candle_01_NoLight_C::BloomPlane4' has a wrong offset!");
static_assert(offsetof(AApollo_Candle_01_NoLight_C, BloomPlane3) == 0x000BB8, "Member 'AApollo_Candle_01_NoLight_C::BloomPlane3' has a wrong offset!");
static_assert(offsetof(AApollo_Candle_01_NoLight_C, BloomPlane2) == 0x000BC0, "Member 'AApollo_Candle_01_NoLight_C::BloomPlane2' has a wrong offset!");
static_assert(offsetof(AApollo_Candle_01_NoLight_C, BloomPlane1) == 0x000BC8, "Member 'AApollo_Candle_01_NoLight_C::BloomPlane1' has a wrong offset!");
static_assert(offsetof(AApollo_Candle_01_NoLight_C, Flame5) == 0x000BD0, "Member 'AApollo_Candle_01_NoLight_C::Flame5' has a wrong offset!");
static_assert(offsetof(AApollo_Candle_01_NoLight_C, Flame4) == 0x000BD8, "Member 'AApollo_Candle_01_NoLight_C::Flame4' has a wrong offset!");
static_assert(offsetof(AApollo_Candle_01_NoLight_C, Flame3) == 0x000BE0, "Member 'AApollo_Candle_01_NoLight_C::Flame3' has a wrong offset!");
static_assert(offsetof(AApollo_Candle_01_NoLight_C, Flame2) == 0x000BE8, "Member 'AApollo_Candle_01_NoLight_C::Flame2' has a wrong offset!");
static_assert(offsetof(AApollo_Candle_01_NoLight_C, Flame1) == 0x000BF0, "Member 'AApollo_Candle_01_NoLight_C::Flame1' has a wrong offset!");

}

