#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_WateringHole_Instrument_Play

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_WateringHole_Instrument_Play.Apollo_WateringHole_Instrument_Play_C
// 0x0020 (0x0BC8 - 0x0BA8)
class AApollo_WateringHole_Instrument_Play_C final : public ABuildingProp
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BA8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          CanThePlayerInteract;                              // 0x0BB0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_BB1[0x7];                                      // 0x0BB1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_WateringHole_AmbTrigger_C*          MusicController;                                   // 0x0BB8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          HiddenMusicActivated;                              // 0x0BC0(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)

public:
	void ExecuteUbergraph_Apollo_WateringHole_Instrument_Play(int32 EntryPoint);
	void ReceiveBeginPlay();
	void BlueprintOnInteract(const class AFortPawn* InteractingPawn, const EInteractionBeingAttempted InteractionBeingAttempted);
	void OnRep_HiddenMusicActivated();

	bool BlueprintCanInteract(const class AFortPawn* InteractingPawn, const EInteractionBeingAttempted InteractionBeingAttempted, const ETInteractionType InteractionType) const;
	class FText BlueprintGetInteractionString(const class AFortPawn* InteractingPawn, const EInteractionBeingAttempted InteractionBeingAttempted) const;
	void GetIconPlacement(const class AActor* SelfActor, const class AActor* ViewingActor, struct FVector* OutLocation, struct FVector* OutExtents) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Apollo_WateringHole_Instrument_Play_C">();
	}
	static class AApollo_WateringHole_Instrument_Play_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_WateringHole_Instrument_Play_C>();
	}
};
static_assert(alignof(AApollo_WateringHole_Instrument_Play_C) == 0x000008, "Wrong alignment on AApollo_WateringHole_Instrument_Play_C");
static_assert(sizeof(AApollo_WateringHole_Instrument_Play_C) == 0x000BC8, "Wrong size on AApollo_WateringHole_Instrument_Play_C");
static_assert(offsetof(AApollo_WateringHole_Instrument_Play_C, UberGraphFrame) == 0x000BA8, "Member 'AApollo_WateringHole_Instrument_Play_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AApollo_WateringHole_Instrument_Play_C, CanThePlayerInteract) == 0x000BB0, "Member 'AApollo_WateringHole_Instrument_Play_C::CanThePlayerInteract' has a wrong offset!");
static_assert(offsetof(AApollo_WateringHole_Instrument_Play_C, MusicController) == 0x000BB8, "Member 'AApollo_WateringHole_Instrument_Play_C::MusicController' has a wrong offset!");
static_assert(offsetof(AApollo_WateringHole_Instrument_Play_C, HiddenMusicActivated) == 0x000BC0, "Member 'AApollo_WateringHole_Instrument_Play_C::HiddenMusicActivated' has a wrong offset!");

}

