#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_Waterbody_Lake_Parent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortWaterBodyBP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_Waterbody_Lake_Parent.Apollo_Waterbody_Lake_Parent_C
// 0x0020 (0x0FC0 - 0x0FA0)
class AApollo_Waterbody_Lake_Parent_C final : public AFortWaterBodyBP_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Apollo_Waterbody_Lake_Parent_C;     // 0x0F98(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UFortSplineWaterAudioComponent*         FortSplineWaterAudio;                              // 0x0FA0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<struct FSplineWaterAudioZone>          InsideAudioExclusionZones;                         // 0x0FA8(0x0010)(Edit, BlueprintVisible, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void ReceiveBeginPlay();
	void ExecuteUbergraph_Apollo_Waterbody_Lake_Parent(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Apollo_Waterbody_Lake_Parent_C">();
	}
	static class AApollo_Waterbody_Lake_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_Waterbody_Lake_Parent_C>();
	}
};
static_assert(alignof(AApollo_Waterbody_Lake_Parent_C) == 0x000010, "Wrong alignment on AApollo_Waterbody_Lake_Parent_C");
static_assert(sizeof(AApollo_Waterbody_Lake_Parent_C) == 0x000FC0, "Wrong size on AApollo_Waterbody_Lake_Parent_C");
static_assert(offsetof(AApollo_Waterbody_Lake_Parent_C, UberGraphFrame_Apollo_Waterbody_Lake_Parent_C) == 0x000F98, "Member 'AApollo_Waterbody_Lake_Parent_C::UberGraphFrame_Apollo_Waterbody_Lake_Parent_C' has a wrong offset!");
static_assert(offsetof(AApollo_Waterbody_Lake_Parent_C, FortSplineWaterAudio) == 0x000FA0, "Member 'AApollo_Waterbody_Lake_Parent_C::FortSplineWaterAudio' has a wrong offset!");
static_assert(offsetof(AApollo_Waterbody_Lake_Parent_C, InsideAudioExclusionZones) == 0x000FA8, "Member 'AApollo_Waterbody_Lake_Parent_C::InsideAudioExclusionZones' has a wrong offset!");

}

