#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_HighTower_SLC_Monitor_01

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_HighTower_SLC_Monitor_01.Apollo_HighTower_SLC_Monitor_01_C
// 0x0010 (0x0BB8 - 0x0BA8)
class AApollo_HighTower_SLC_Monitor_01_C final : public ABuildingProp
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BA8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAudioComponent*                        Monitor_Ambient_Audio;                             // 0x0BB0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Apollo_HighTower_SLC_Monitor_01(int32 EntryPoint);
	void OnDeathPlayEffects(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AFortPawn* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Apollo_HighTower_SLC_Monitor_01_C">();
	}
	static class AApollo_HighTower_SLC_Monitor_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_HighTower_SLC_Monitor_01_C>();
	}
};
static_assert(alignof(AApollo_HighTower_SLC_Monitor_01_C) == 0x000008, "Wrong alignment on AApollo_HighTower_SLC_Monitor_01_C");
static_assert(sizeof(AApollo_HighTower_SLC_Monitor_01_C) == 0x000BB8, "Wrong size on AApollo_HighTower_SLC_Monitor_01_C");
static_assert(offsetof(AApollo_HighTower_SLC_Monitor_01_C, UberGraphFrame) == 0x000BA8, "Member 'AApollo_HighTower_SLC_Monitor_01_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AApollo_HighTower_SLC_Monitor_01_C, Monitor_Ambient_Audio) == 0x000BB0, "Member 'AApollo_HighTower_SLC_Monitor_01_C::Monitor_Ambient_Audio' has a wrong offset!");

}

