#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_Boardwalk_Stair4

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_Boardwalk_Stair4.Apollo_Boardwalk_Stair4_C
// 0x0018 (0x0AE8 - 0x0AD0)
class AApollo_Boardwalk_Stair4_C final : public ABuildingStairs
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AD0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAudioComponent*                        WoodCreakSound;                                    // 0x0AD8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             WoodCreakLoop_SoundCueSetting;                     // 0x0AE0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Apollo_Boardwalk_Stair4(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Apollo_Boardwalk_Stair4_C">();
	}
	static class AApollo_Boardwalk_Stair4_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_Boardwalk_Stair4_C>();
	}
};
static_assert(alignof(AApollo_Boardwalk_Stair4_C) == 0x000008, "Wrong alignment on AApollo_Boardwalk_Stair4_C");
static_assert(sizeof(AApollo_Boardwalk_Stair4_C) == 0x000AE8, "Wrong size on AApollo_Boardwalk_Stair4_C");
static_assert(offsetof(AApollo_Boardwalk_Stair4_C, UberGraphFrame) == 0x000AD0, "Member 'AApollo_Boardwalk_Stair4_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AApollo_Boardwalk_Stair4_C, WoodCreakSound) == 0x000AD8, "Member 'AApollo_Boardwalk_Stair4_C::WoodCreakSound' has a wrong offset!");
static_assert(offsetof(AApollo_Boardwalk_Stair4_C, WoodCreakLoop_SoundCueSetting) == 0x000AE0, "Member 'AApollo_Boardwalk_Stair4_C::WoodCreakLoop_SoundCueSetting' has a wrong offset!");

}

