#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_Order_Pillar

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_Order_Pillar.Apollo_Order_Pillar_C
// 0x0000 (0x0AC8 - 0x0AC8)
class AApollo_Order_Pillar_C final : public ABuildingPillar
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Apollo_Order_Pillar_C">();
	}
	static class AApollo_Order_Pillar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_Order_Pillar_C>();
	}
};
static_assert(alignof(AApollo_Order_Pillar_C) == 0x000008, "Wrong alignment on AApollo_Order_Pillar_C");
static_assert(sizeof(AApollo_Order_Pillar_C) == 0x000AC8, "Wrong size on AApollo_Order_Pillar_C");

}

