#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_HH_Cosmos_Carbonite_01

#include "Basic.hpp"

#include "Apollo_HH_Cosmos_Carbonite_01_classes.hpp"
#include "Apollo_HH_Cosmos_Carbonite_01_parameters.hpp"


namespace SDK
{

// Function Apollo_HH_Cosmos_Carbonite_01.Apollo_HH_Cosmos_Carbonite_01_C.ExecuteUbergraph_Apollo_HH_Cosmos_Carbonite_01
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AApollo_HH_Cosmos_Carbonite_01_C::ExecuteUbergraph_Apollo_HH_Cosmos_Carbonite_01(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_Apollo_HH_Cosmos_Carbonite_01");

	Params::Apollo_HH_Cosmos_Carbonite_01_C_ExecuteUbergraph_Apollo_HH_Cosmos_Carbonite_01 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Apollo_HH_Cosmos_Carbonite_01.Apollo_HH_Cosmos_Carbonite_01_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AApollo_HH_Cosmos_Carbonite_01_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveEndPlay");

	Params::Apollo_HH_Cosmos_Carbonite_01_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}

}

