#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaQuestActor_CarPart

#include "Basic.hpp"

#include "AthenaQuestActor_CarPart_classes.hpp"
#include "AthenaQuestActor_CarPart_parameters.hpp"


namespace SDK
{

// Function AthenaQuestActor_CarPart.AthenaQuestActor_CarPart_C.ExecuteUbergraph_AthenaQuestActor_CarPart
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthenaQuestActor_CarPart_C::ExecuteUbergraph_AthenaQuestActor_CarPart(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_AthenaQuestActor_CarPart");

	Params::AthenaQuestActor_CarPart_C_ExecuteUbergraph_AthenaQuestActor_CarPart Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaQuestActor_CarPart.AthenaQuestActor_CarPart_C.OnObjectiveCompleteForPlayer
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortQuestObjectiveInfo*          ObjectiveInfo                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AFortPlayerController*            PCOverrideForVisualTesting                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthenaQuestActor_CarPart_C::OnObjectiveCompleteForPlayer(class UFortQuestObjectiveInfo* ObjectiveInfo, class AFortPlayerController* PCOverrideForVisualTesting)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnObjectiveCompleteForPlayer");

	Params::AthenaQuestActor_CarPart_C_OnObjectiveCompleteForPlayer Parms{};

	Parms.ObjectiveInfo = ObjectiveInfo;
	Parms.PCOverrideForVisualTesting = PCOverrideForVisualTesting;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaQuestActor_CarPart.AthenaQuestActor_CarPart_C.OnQuestEnabledForPlayer
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerController*            FortPlayerController                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthenaQuestActor_CarPart_C::OnQuestEnabledForPlayer(class AFortPlayerController* FortPlayerController)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnQuestEnabledForPlayer");

	Params::AthenaQuestActor_CarPart_C_OnQuestEnabledForPlayer Parms{};

	Parms.FortPlayerController = FortPlayerController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaQuestActor_CarPart.AthenaQuestActor_CarPart_C.SetPrimitiveGroupsToHide
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UPrimitiveComponent*>      PrimitivesToHideByDefault_0                            (Parm, OutParm, ContainsInstancedReference, HasGetValueTypeHash)
// TArray<class UPrimitiveComponent*>      PrimitivesToShowIfQuestComplete_0                      (Parm, OutParm, ContainsInstancedReference, HasGetValueTypeHash)
// TArray<class UPrimitiveComponent*>      PrimitivesToShowIfQuestInProgress_0                    (Parm, OutParm, ContainsInstancedReference, HasGetValueTypeHash)

void AAthenaQuestActor_CarPart_C::SetPrimitiveGroupsToHide(TArray<class UPrimitiveComponent*>* PrimitivesToHideByDefault_0, TArray<class UPrimitiveComponent*>* PrimitivesToShowIfQuestComplete_0, TArray<class UPrimitiveComponent*>* PrimitivesToShowIfQuestInProgress_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetPrimitiveGroupsToHide");

	Params::AthenaQuestActor_CarPart_C_SetPrimitiveGroupsToHide Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PrimitivesToHideByDefault_0 != nullptr)
		*PrimitivesToHideByDefault_0 = std::move(Parms.PrimitivesToHideByDefault_0);

	if (PrimitivesToShowIfQuestComplete_0 != nullptr)
		*PrimitivesToShowIfQuestComplete_0 = std::move(Parms.PrimitivesToShowIfQuestComplete_0);

	if (PrimitivesToShowIfQuestInProgress_0 != nullptr)
		*PrimitivesToShowIfQuestInProgress_0 = std::move(Parms.PrimitivesToShowIfQuestInProgress_0);
}


// Function AthenaQuestActor_CarPart.AthenaQuestActor_CarPart_C.SetAdditionalQuestsRequiredOnProfile
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UFortQuestItemDefinition*> QuestsRequiredOnProfile_0                              (Parm, OutParm, HasGetValueTypeHash)

void AAthenaQuestActor_CarPart_C::SetAdditionalQuestsRequiredOnProfile(TArray<class UFortQuestItemDefinition*>* QuestsRequiredOnProfile_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetAdditionalQuestsRequiredOnProfile");

	Params::AthenaQuestActor_CarPart_C_SetAdditionalQuestsRequiredOnProfile Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (QuestsRequiredOnProfile_0 != nullptr)
		*QuestsRequiredOnProfile_0 = std::move(Parms.QuestsRequiredOnProfile_0);
}


// Function AthenaQuestActor_CarPart.AthenaQuestActor_CarPart_C.BlueprintGetInteractionString
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class AFortPawn*                        InteractingPawn                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EInteractionBeingAttempted              InteractionBeingAttempted                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText AAthenaQuestActor_CarPart_C::BlueprintGetInteractionString(const class AFortPawn* InteractingPawn, const EInteractionBeingAttempted InteractionBeingAttempted) const
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BlueprintGetInteractionString");

	Params::AthenaQuestActor_CarPart_C_BlueprintGetInteractionString Parms{};

	Parms.InteractingPawn = InteractingPawn;
	Parms.InteractionBeingAttempted = InteractionBeingAttempted;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

