#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaItemDetailsHeader

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function AthenaItemDetailsHeader.AthenaItemDetailsHeader_C.ExecuteUbergraph_AthenaItemDetailsHeader
// 0x0028 (0x0028 - 0x0000)
struct AthenaItemDetailsHeader_C_ExecuteUbergraph_AthenaItemDetailsHeader final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue;           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortGameStateAthena*                   CallFunc_GetGameStateAthena_ReturnValue;           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsCreativeOrPlaygroundModePlaylist_ReturnValue; // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_GetDynamicMaterial_ReturnValue_1;         // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaItemDetailsHeader_C_ExecuteUbergraph_AthenaItemDetailsHeader) == 0x000008, "Wrong alignment on AthenaItemDetailsHeader_C_ExecuteUbergraph_AthenaItemDetailsHeader");
static_assert(sizeof(AthenaItemDetailsHeader_C_ExecuteUbergraph_AthenaItemDetailsHeader) == 0x000028, "Wrong size on AthenaItemDetailsHeader_C_ExecuteUbergraph_AthenaItemDetailsHeader");
static_assert(offsetof(AthenaItemDetailsHeader_C_ExecuteUbergraph_AthenaItemDetailsHeader, EntryPoint) == 0x000000, "Member 'AthenaItemDetailsHeader_C_ExecuteUbergraph_AthenaItemDetailsHeader::EntryPoint' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_ExecuteUbergraph_AthenaItemDetailsHeader, CallFunc_GetDynamicMaterial_ReturnValue) == 0x000008, "Member 'AthenaItemDetailsHeader_C_ExecuteUbergraph_AthenaItemDetailsHeader::CallFunc_GetDynamicMaterial_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_ExecuteUbergraph_AthenaItemDetailsHeader, CallFunc_GetGameStateAthena_ReturnValue) == 0x000010, "Member 'AthenaItemDetailsHeader_C_ExecuteUbergraph_AthenaItemDetailsHeader::CallFunc_GetGameStateAthena_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_ExecuteUbergraph_AthenaItemDetailsHeader, CallFunc_IsCreativeOrPlaygroundModePlaylist_ReturnValue) == 0x000018, "Member 'AthenaItemDetailsHeader_C_ExecuteUbergraph_AthenaItemDetailsHeader::CallFunc_IsCreativeOrPlaygroundModePlaylist_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_ExecuteUbergraph_AthenaItemDetailsHeader, CallFunc_GetDynamicMaterial_ReturnValue_1) == 0x000020, "Member 'AthenaItemDetailsHeader_C_ExecuteUbergraph_AthenaItemDetailsHeader::CallFunc_GetDynamicMaterial_ReturnValue_1' has a wrong offset!");

// Function AthenaItemDetailsHeader.AthenaItemDetailsHeader_C.UpdateItemsForWidgets
// 0x0640 (0x0640 - 0x0000)
struct AthenaItemDetailsHeader_C_UpdateItemsForWidgets final
{
public:
	int32                                         CallFunc_GetNumInStack_ReturnValue;                // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortItemType                                 CallFunc_GetType_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0008(0x0018)()
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0028(0x0040)(HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0070(0x0010)(ReferenceParm, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0088(0x0018)()
	bool                                          Temp_bool_Variable;                                // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x00A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortRarity                                   CallFunc_GetRarityCosmeticForItem_ReturnValue;     // 0x00A2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x00A3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x00A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x00A5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x00A6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A7[0x1];                                       // 0x00A7(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetDisplayName_ReturnValue;               // 0x00A8(0x0018)()
	bool                                          Temp_bool_Variable_2;                              // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C1[0x3];                                       // 0x00C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C9[0x7];                                       // 0x00C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              CallFunc_GetSmallPreviewImage_ReturnValue;         // 0x00D0(0x0028)(HasGetValueTypeHash)
	class FText                                   CallFunc_GetDisplayName_ReturnValue_1;             // 0x00F8(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0110(0x0040)(HasGetValueTypeHash)
	int32                                         CallFunc_GetNumInStack_ReturnValue_1;              // 0x0150(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_154[0x4];                                      // 0x0154(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x0158(0x0010)(ReferenceParm, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue_1;             // 0x0168(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x0180(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_2;            // 0x0198(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_2;                          // 0x01D8(0x0010)(ReferenceParm, HasGetValueTypeHash)
	class FText                                   CallFunc_Format_ReturnValue_2;                     // 0x01E8(0x0018)()
	ESubGame                                      CallFunc_GetSubGame_ReturnValue;                   // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0201(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_202[0x6];                                      // 0x0202(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EFortItemType>                         K2Node_MakeArray_Array_3;                          // 0x0208(0x0010)(ConstParm, ReferenceParm, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0218(0x0028)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0240(0x0028)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_3;            // 0x0268(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_4;                          // 0x02A8(0x0010)(ReferenceParm, HasGetValueTypeHash)
	class FText                                   CallFunc_Format_ReturnValue_3;                     // 0x02B8(0x0018)()
	class UFortItemDefinition*                    CallFunc_GetSchematicCraftingResultBP_ReturnValue; // 0x02D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortWeaponItemDefinition*              K2Node_DynamicCast_AsFort_Weapon_Item_Definition;  // 0x02D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x02E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2E1[0x7];                                      // 0x02E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EFortItemType>                         K2Node_MakeArray_Array_5;                          // 0x02E8(0x0010)(ConstParm, ReferenceParm, HasGetValueTypeHash)
	float                                         Temp_float_Variable;                               // 0x02F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortItemType                                 CallFunc_GetSchematicResultType_ReturnValue;       // 0x02FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2FD[0x3];                                      // 0x02FD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortItemDefinition*                    CallFunc_GetSchematicCraftingResultBP_ReturnValue_1; // 0x0300(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortItemType                                 CallFunc_GetType_ReturnValue_1;                    // 0x0308(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0309(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x030A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EFortItemType                                 K2Node_Select_Default;                             // 0x030B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_Contains_ReturnValue;               // 0x030C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EFortRarity                                   CallFunc_GetRarityCosmeticForItem_ReturnValue_1;   // 0x030D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x030E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_30F[0x1];                                      // 0x030F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFortRarityItemData                    CallFunc_BPGetRarityData_ReturnValue;              // 0x0310(0x0080)()
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0390(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EFortItemType                                 CallFunc_GetType_ReturnValue_2;                    // 0x0391(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x0392(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_2;        // 0x0393(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_3;        // 0x0394(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0395(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x0396(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x0397(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Array_Contains_ReturnValue_1;             // 0x0398(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_399[0x3];                                      // 0x0399(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Select_Default_2;                           // 0x039C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_3;                           // 0x03A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A1[0x3];                                      // 0x03A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable_1;                             // 0x03A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_2;                             // 0x03A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_3;                             // 0x03AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_4;                             // 0x03B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_5;                             // 0x03B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_6;                             // 0x03B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortItemTier                                 CallFunc_GetTier_ReturnValue;                      // 0x03BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x03BD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3BE[0x2];                                      // 0x03BE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Convert_Tier_To_Integer_Numeric_Tier;     // 0x03C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_7;                             // 0x03C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortRarity                                   Temp_byte_Variable_4;                              // 0x03C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C9[0x3];                                      // 0x03C9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select_Default_4;                           // 0x03CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_GetNumberOfSlotsTaken_ReturnValue;        // 0x03D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D1[0x3];                                      // 0x03D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetNumInStack_ReturnValue_2;              // 0x03D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x03D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x03DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3DD[0x3];                                      // 0x03DD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_4;            // 0x03E0(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_6;                          // 0x0420(0x0010)(ReferenceParm, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue_2;             // 0x0430(0x0018)()
	class FText                                   CallFunc_Format_ReturnValue_4;                     // 0x0448(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_5;            // 0x0460(0x0040)(HasGetValueTypeHash)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_7;                          // 0x04A0(0x0010)(ReferenceParm, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_ByteByte_ReturnValue;        // 0x04B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4B1[0x7];                                      // 0x04B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Format_ReturnValue_5;                     // 0x04B8(0x0018)()
	class UFortItemDefinition*                    CallFunc_GetItemDefinitionBP_ReturnValue;          // 0x04D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetLoadedAmmo_ReturnValue;                // 0x04D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4DC[0x4];                                      // 0x04DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortWeaponItemDefinition*              K2Node_DynamicCast_AsFort_Weapon_Item_Definition_1; // 0x04E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x04E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x04E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4EA[0x6];                                      // 0x04EA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortWorldItemDefinition*               CallFunc_GetAmmoWorldItemDefinition_BP_ReturnValue; // 0x04F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x04F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4F9[0x7];                                      // 0x04F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Conv_IntToText_ReturnValue_3;             // 0x0500(0x0018)()
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_6;            // 0x0518(0x0040)(HasGetValueTypeHash)
	int32                                         CallFunc_GetNumInStack_ReturnValue_3;              // 0x0558(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_55C[0x4];                                      // 0x055C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_8;                          // 0x0560(0x0010)(ReferenceParm, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0570(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_571[0x7];                                      // 0x0571(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Format_ReturnValue_6;                     // 0x0578(0x0018)()
	class FText                                   CallFunc_Conv_IntToText_ReturnValue_4;             // 0x0590(0x0018)()
	class UFortItemDefinition*                    CallFunc_GetItemDefinitionBP_ReturnValue_1;        // 0x05A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_7;            // 0x05B0(0x0040)(HasGetValueTypeHash)
	class UFortWeaponItemDefinition*              K2Node_DynamicCast_AsFort_Weapon_Item_Definition_2; // 0x05F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x05F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5F9[0x7];                                      // 0x05F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_9;                          // 0x0600(0x0010)(ReferenceParm, HasGetValueTypeHash)
	bool                                          CallFunc_HasUniqueAmmo_ReturnValue;                // 0x0610(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_611[0x7];                                      // 0x0611(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Format_ReturnValue_7;                     // 0x0618(0x0018)()
	bool                                          CallFunc_IsDroppedItem_ReturnValue;                // 0x0630(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EFortItemTier                                 CallFunc_GetTier_ReturnValue_1;                    // 0x0631(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_632[0x2];                                      // 0x0632(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Convert_Tier_To_Integer_Numeric_Tier_1;   // 0x0634(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0638(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets) == 0x000008, "Wrong alignment on AthenaItemDetailsHeader_C_UpdateItemsForWidgets");
static_assert(sizeof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets) == 0x000640, "Wrong size on AthenaItemDetailsHeader_C_UpdateItemsForWidgets");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetNumInStack_ReturnValue) == 0x000000, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetNumInStack_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetType_ReturnValue) == 0x000004, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetType_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Conv_IntToText_ReturnValue) == 0x000008, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000020, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeStruct_FormatArgumentData) == 0x000028, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeStruct_FormatArgumentData' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x000068, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeArray_Array) == 0x000070, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_BooleanOR_ReturnValue) == 0x000080, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Format_ReturnValue) == 0x000088, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Format_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_bool_Variable) == 0x0000A0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_byte_Variable) == 0x0000A1, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetRarityCosmeticForItem_ReturnValue) == 0x0000A2, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetRarityCosmeticForItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_byte_Variable_1) == 0x0000A3, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_bool_Variable_1) == 0x0000A4, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_byte_Variable_2) == 0x0000A5, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_byte_Variable_3) == 0x0000A6, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetDisplayName_ReturnValue) == 0x0000A8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_bool_Variable_2) == 0x0000C0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_int_Variable) == 0x0000C4, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_bool_Variable_3) == 0x0000C8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetSmallPreviewImage_ReturnValue) == 0x0000D0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetSmallPreviewImage_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetDisplayName_ReturnValue_1) == 0x0000F8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetDisplayName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeStruct_FormatArgumentData_1) == 0x000110, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeStruct_FormatArgumentData_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetNumInStack_ReturnValue_1) == 0x000150, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetNumInStack_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeArray_Array_1) == 0x000158, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Conv_IntToText_ReturnValue_1) == 0x000168, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Conv_IntToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Format_ReturnValue_1) == 0x000180, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Format_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeStruct_FormatArgumentData_2) == 0x000198, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeStruct_FormatArgumentData_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeArray_Array_2) == 0x0001D8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeArray_Array_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Format_ReturnValue_2) == 0x0001E8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Format_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetSubGame_ReturnValue) == 0x000200, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetSubGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_SwitchEnum_CmpSuccess) == 0x000201, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeArray_Array_3) == 0x000208, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeArray_Array_3' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeStruct_SlateColor) == 0x000218, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeStruct_SlateColor' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeStruct_SlateColor_1) == 0x000240, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeStruct_SlateColor_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeStruct_FormatArgumentData_3) == 0x000268, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeStruct_FormatArgumentData_3' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeArray_Array_4) == 0x0002A8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeArray_Array_4' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Format_ReturnValue_3) == 0x0002B8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Format_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetSchematicCraftingResultBP_ReturnValue) == 0x0002D0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetSchematicCraftingResultBP_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_DynamicCast_AsFort_Weapon_Item_Definition) == 0x0002D8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_DynamicCast_AsFort_Weapon_Item_Definition' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_DynamicCast_bSuccess) == 0x0002E0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeArray_Array_5) == 0x0002E8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeArray_Array_5' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_float_Variable) == 0x0002F8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetSchematicResultType_ReturnValue) == 0x0002FC, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetSchematicResultType_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetSchematicCraftingResultBP_ReturnValue_1) == 0x000300, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetSchematicCraftingResultBP_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetType_ReturnValue_1) == 0x000308, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetType_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_IsValid_ReturnValue) == 0x000309, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Not_PreBool_ReturnValue) == 0x00030A, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_Select_Default) == 0x00030B, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Array_Contains_ReturnValue) == 0x00030C, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Array_Contains_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetRarityCosmeticForItem_ReturnValue_1) == 0x00030D, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetRarityCosmeticForItem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_BooleanAND_ReturnValue) == 0x00030E, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_BPGetRarityData_ReturnValue) == 0x000310, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_BPGetRarityData_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_BooleanAND_ReturnValue_1) == 0x000390, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetType_ReturnValue_2) == 0x000391, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetType_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_Select_Default_1) == 0x000392, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_EqualEqual_ByteByte_ReturnValue_2) == 0x000393, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_EqualEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_EqualEqual_ByteByte_ReturnValue_3) == 0x000394, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_EqualEqual_ByteByte_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_IsValid_ReturnValue_1) == 0x000395, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_BooleanOR_ReturnValue_1) == 0x000396, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_BooleanAND_ReturnValue_2) == 0x000397, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Array_Contains_ReturnValue_1) == 0x000398, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Array_Contains_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_Select_Default_2) == 0x00039C, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_Select_Default_3) == 0x0003A0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_float_Variable_1) == 0x0003A4, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_float_Variable_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_float_Variable_2) == 0x0003A8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_float_Variable_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_float_Variable_3) == 0x0003AC, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_float_Variable_3' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_float_Variable_4) == 0x0003B0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_float_Variable_4' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_float_Variable_5) == 0x0003B4, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_float_Variable_5' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_float_Variable_6) == 0x0003B8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_float_Variable_6' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetTier_ReturnValue) == 0x0003BC, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetTier_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_IsValid_ReturnValue_2) == 0x0003BD, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Convert_Tier_To_Integer_Numeric_Tier) == 0x0003C0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Convert_Tier_To_Integer_Numeric_Tier' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_float_Variable_7) == 0x0003C4, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_float_Variable_7' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, Temp_byte_Variable_4) == 0x0003C8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::Temp_byte_Variable_4' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_Select_Default_4) == 0x0003CC, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_Select_Default_4' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetNumberOfSlotsTaken_ReturnValue) == 0x0003D0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetNumberOfSlotsTaken_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetNumInStack_ReturnValue_2) == 0x0003D4, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetNumInStack_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Conv_ByteToInt_ReturnValue) == 0x0003D8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Less_IntInt_ReturnValue) == 0x0003DC, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeStruct_FormatArgumentData_4) == 0x0003E0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeStruct_FormatArgumentData_4' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeArray_Array_6) == 0x000420, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeArray_Array_6' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Conv_IntToText_ReturnValue_2) == 0x000430, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Conv_IntToText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Format_ReturnValue_4) == 0x000448, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Format_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeStruct_FormatArgumentData_5) == 0x000460, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeStruct_FormatArgumentData_5' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeArray_Array_7) == 0x0004A0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeArray_Array_7' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GreaterEqual_ByteByte_ReturnValue) == 0x0004B0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GreaterEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Format_ReturnValue_5) == 0x0004B8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Format_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetItemDefinitionBP_ReturnValue) == 0x0004D0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetItemDefinitionBP_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetLoadedAmmo_ReturnValue) == 0x0004D8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetLoadedAmmo_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_DynamicCast_AsFort_Weapon_Item_Definition_1) == 0x0004E0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_DynamicCast_AsFort_Weapon_Item_Definition_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_DynamicCast_bSuccess_1) == 0x0004E8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Less_IntInt_ReturnValue_1) == 0x0004E9, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetAmmoWorldItemDefinition_BP_ReturnValue) == 0x0004F0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetAmmoWorldItemDefinition_BP_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x0004F8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Conv_IntToText_ReturnValue_3) == 0x000500, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Conv_IntToText_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeStruct_FormatArgumentData_6) == 0x000518, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeStruct_FormatArgumentData_6' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetNumInStack_ReturnValue_3) == 0x000558, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetNumInStack_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeArray_Array_8) == 0x000560, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeArray_Array_8' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Less_IntInt_ReturnValue_2) == 0x000570, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Format_ReturnValue_6) == 0x000578, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Format_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Conv_IntToText_ReturnValue_4) == 0x000590, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Conv_IntToText_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetItemDefinitionBP_ReturnValue_1) == 0x0005A8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetItemDefinitionBP_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeStruct_FormatArgumentData_7) == 0x0005B0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeStruct_FormatArgumentData_7' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_DynamicCast_AsFort_Weapon_Item_Definition_2) == 0x0005F0, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_DynamicCast_AsFort_Weapon_Item_Definition_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_DynamicCast_bSuccess_2) == 0x0005F8, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, K2Node_MakeArray_Array_9) == 0x000600, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::K2Node_MakeArray_Array_9' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_HasUniqueAmmo_ReturnValue) == 0x000610, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_HasUniqueAmmo_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Format_ReturnValue_7) == 0x000618, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Format_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_IsDroppedItem_ReturnValue) == 0x000630, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_IsDroppedItem_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_GetTier_ReturnValue_1) == 0x000631, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_GetTier_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Convert_Tier_To_Integer_Numeric_Tier_1) == 0x000634, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Convert_Tier_To_Integer_Numeric_Tier_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_UpdateItemsForWidgets, CallFunc_Subtract_IntInt_ReturnValue) == 0x000638, "Member 'AthenaItemDetailsHeader_C_UpdateItemsForWidgets::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");

// Function AthenaItemDetailsHeader.AthenaItemDetailsHeader_C.SetItemCost
// 0x0030 (0x0030 - 0x0000)
struct AthenaItemDetailsHeader_C_SetItemCost final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 Temp_class_Variable;                               // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 Temp_class_Variable_1;                             // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsCreativeOrPlaygroundModePlaylist_ReturnValue; // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 K2Node_Select_Default;                             // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaItemDetailsHeader_C_SetItemCost) == 0x000008, "Wrong alignment on AthenaItemDetailsHeader_C_SetItemCost");
static_assert(sizeof(AthenaItemDetailsHeader_C_SetItemCost) == 0x000030, "Wrong size on AthenaItemDetailsHeader_C_SetItemCost");
static_assert(offsetof(AthenaItemDetailsHeader_C_SetItemCost, Actor) == 0x000000, "Member 'AthenaItemDetailsHeader_C_SetItemCost::Actor' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_SetItemCost, Temp_bool_Variable) == 0x000008, "Member 'AthenaItemDetailsHeader_C_SetItemCost::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_SetItemCost, Temp_class_Variable) == 0x000010, "Member 'AthenaItemDetailsHeader_C_SetItemCost::Temp_class_Variable' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_SetItemCost, Temp_class_Variable_1) == 0x000018, "Member 'AthenaItemDetailsHeader_C_SetItemCost::Temp_class_Variable_1' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_SetItemCost, CallFunc_IsCreativeOrPlaygroundModePlaylist_ReturnValue) == 0x000020, "Member 'AthenaItemDetailsHeader_C_SetItemCost::CallFunc_IsCreativeOrPlaygroundModePlaylist_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaItemDetailsHeader_C_SetItemCost, K2Node_Select_Default) == 0x000028, "Member 'AthenaItemDetailsHeader_C_SetItemCost::K2Node_Select_Default' has a wrong offset!");

}

