#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_Anniversary_Cake

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Athena_Anniversary_Cake.Athena_Anniversary_Cake_C.ExecuteUbergraph_Athena_Anniversary_Cake
// 0x0010 (0x0010 - 0x0000)
struct Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EEvaluateCurveTableResult                     CallFunc_EvaluateCurveTableRow_OutResult;          // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_EvaluateCurveTableRow_OutXY;              // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x000D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake) == 0x000004, "Wrong alignment on Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake");
static_assert(sizeof(Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake) == 0x000010, "Wrong size on Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake");
static_assert(offsetof(Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake, EntryPoint) == 0x000000, "Member 'Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake::EntryPoint' has a wrong offset!");
static_assert(offsetof(Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake, CallFunc_HasAuthority_ReturnValue) == 0x000004, "Member 'Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake, CallFunc_EvaluateCurveTableRow_OutResult) == 0x000005, "Member 'Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake::CallFunc_EvaluateCurveTableRow_OutResult' has a wrong offset!");
static_assert(offsetof(Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake, CallFunc_EvaluateCurveTableRow_OutXY) == 0x000008, "Member 'Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake::CallFunc_EvaluateCurveTableRow_OutXY' has a wrong offset!");
static_assert(offsetof(Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake, CallFunc_Greater_FloatFloat_ReturnValue) == 0x00000C, "Member 'Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake, K2Node_SwitchEnum_CmpSuccess) == 0x00000D, "Member 'Athena_Anniversary_Cake_C_ExecuteUbergraph_Athena_Anniversary_Cake::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");

}

