#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_Anniversary_Balloons

#include "Basic.hpp"

#include "Athena_Anniversary_Balloons_classes.hpp"
#include "Athena_Anniversary_Balloons_parameters.hpp"


namespace SDK
{

// Function Athena_Anniversary_Balloons.Athena_Anniversary_Balloons_C.ExecuteUbergraph_Athena_Anniversary_Balloons
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthena_Anniversary_Balloons_C::ExecuteUbergraph_Athena_Anniversary_Balloons(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_Athena_Anniversary_Balloons");

	Params::Athena_Anniversary_Balloons_C_ExecuteUbergraph_Athena_Anniversary_Balloons Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Athena_Anniversary_Balloons.Athena_Anniversary_Balloons_C.OnWorldReady
// (Event, Public, BlueprintEvent)

void AAthena_Anniversary_Balloons_C::OnWorldReady()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnWorldReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Athena_Anniversary_Balloons.Athena_Anniversary_Balloons_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AAthena_Anniversary_Balloons_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

