#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaQuestActor_DF_GL1_Graffiti

#include "Basic.hpp"

#include "AthenaQuestActor_DF_GL1_Graffiti_classes.hpp"
#include "AthenaQuestActor_DF_GL1_Graffiti_parameters.hpp"


namespace SDK
{

// Function AthenaQuestActor_DF_GL1_Graffiti.AthenaQuestActor_DF_GL1_Graffiti_C.ExecuteUbergraph_AthenaQuestActor_DF_GL1_Graffiti
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthenaQuestActor_DF_GL1_Graffiti_C::ExecuteUbergraph_AthenaQuestActor_DF_GL1_Graffiti(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_AthenaQuestActor_DF_GL1_Graffiti");

	Params::AthenaQuestActor_DF_GL1_Graffiti_C_ExecuteUbergraph_AthenaQuestActor_DF_GL1_Graffiti Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaQuestActor_DF_GL1_Graffiti.AthenaQuestActor_DF_GL1_Graffiti_C.FoundEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortPlayerController*            PC                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthenaQuestActor_DF_GL1_Graffiti_C::FoundEvent(class AFortPlayerController* PC)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("FoundEvent");

	Params::AthenaQuestActor_DF_GL1_Graffiti_C_FoundEvent Parms{};

	Parms.PC = PC;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaQuestActor_DF_GL1_Graffiti.AthenaQuestActor_DF_GL1_Graffiti_C.TouchedActorInCreativeMode
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void AAthenaQuestActor_DF_GL1_Graffiti_C::TouchedActorInCreativeMode()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TouchedActorInCreativeMode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaQuestActor_DF_GL1_Graffiti.AthenaQuestActor_DF_GL1_Graffiti_C.TellChildOfSuccess
// (BlueprintCallable, BlueprintEvent)

void AAthenaQuestActor_DF_GL1_Graffiti_C::TellChildOfSuccess()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TellChildOfSuccess");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaQuestActor_DF_GL1_Graffiti.AthenaQuestActor_DF_GL1_Graffiti_C.ObjectiveSuccessfullyCompleted
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           PlayerWhoTriggeredObject                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAthenaQuestActor_DF_GL1_Graffiti_C::ObjectiveSuccessfullyCompleted(class AActor* PlayerWhoTriggeredObject)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ObjectiveSuccessfullyCompleted");

	Params::AthenaQuestActor_DF_GL1_Graffiti_C_ObjectiveSuccessfullyCompleted Parms{};

	Parms.PlayerWhoTriggeredObject = PlayerWhoTriggeredObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaQuestActor_DF_GL1_Graffiti.AthenaQuestActor_DF_GL1_Graffiti_C.QuestInitializedAndValid
// (BlueprintCallable, BlueprintEvent)

void AAthenaQuestActor_DF_GL1_Graffiti_C::QuestInitializedAndValid()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("QuestInitializedAndValid");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaQuestActor_DF_GL1_Graffiti.AthenaQuestActor_DF_GL1_Graffiti_C.QuestSuccessfullyUpdated
// (BlueprintCallable, BlueprintEvent)

void AAthenaQuestActor_DF_GL1_Graffiti_C::QuestSuccessfullyUpdated()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("QuestSuccessfullyUpdated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaQuestActor_DF_GL1_Graffiti.AthenaQuestActor_DF_GL1_Graffiti_C.PlaylistLoaded
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             PlaylistName                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTagContainer            PlaylistContextTags                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void AAthenaQuestActor_DF_GL1_Graffiti_C::PlaylistLoaded(class FName PlaylistName, const struct FGameplayTagContainer& PlaylistContextTags)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PlaylistLoaded");

	Params::AthenaQuestActor_DF_GL1_Graffiti_C_PlaylistLoaded Parms{};

	Parms.PlaylistName = PlaylistName;
	Parms.PlaylistContextTags = std::move(PlaylistContextTags);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaQuestActor_DF_GL1_Graffiti.AthenaQuestActor_DF_GL1_Graffiti_C.TouchedQuestActor
// (Net, NetMulticast, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FHitResult                       SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void AAthenaQuestActor_DF_GL1_Graffiti_C::TouchedQuestActor(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TouchedQuestActor");

	Params::AthenaQuestActor_DF_GL1_Graffiti_C_TouchedQuestActor Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaQuestActor_DF_GL1_Graffiti.AthenaQuestActor_DF_GL1_Graffiti_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AAthenaQuestActor_DF_GL1_Graffiti_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaQuestActor_DF_GL1_Graffiti.AthenaQuestActor_DF_GL1_Graffiti_C.OnRep_ShoppingCartThatTriggered
// (BlueprintCallable, BlueprintEvent)

void AAthenaQuestActor_DF_GL1_Graffiti_C::OnRep_ShoppingCartThatTriggered()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnRep_ShoppingCartThatTriggered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaQuestActor_DF_GL1_Graffiti.AthenaQuestActor_DF_GL1_Graffiti_C.CheckShouldShowLocally
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ShouldShowLocally                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AAthenaQuestActor_DF_GL1_Graffiti_C::CheckShouldShowLocally(bool* ShouldShowLocally)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("CheckShouldShowLocally");

	Params::AthenaQuestActor_DF_GL1_Graffiti_C_CheckShouldShowLocally Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ShouldShowLocally != nullptr)
		*ShouldShowLocally = Parms.ShouldShowLocally;
}


// Function AthenaQuestActor_DF_GL1_Graffiti.AthenaQuestActor_DF_GL1_Graffiti_C.OnRep_PlaySuccessFX
// (BlueprintCallable, BlueprintEvent)

void AAthenaQuestActor_DF_GL1_Graffiti_C::OnRep_PlaySuccessFX()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnRep_PlaySuccessFX");

	UObject::ProcessEvent(Func, nullptr);
}

}

