#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaQuestActor_DF_GL1_Graffiti

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AthenaQuestActor_DF_GL1_Graffiti.AthenaQuestActor_DF_GL1_Graffiti_C
// 0x0080 (0x02A0 - 0x0220)
class AAthenaQuestActor_DF_GL1_Graffiti_C final : public AFortStaticReplicatedActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UParticleSystemComponent*               P_Athena_QuestItem_PickupSuccess;                  // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Athena_CollectHiddenStarReward_Cue;                // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCapsuleComponent*                      TouchCapsule;                                      // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UFortQuestItemDefinition*               QuestItem;                                         // 0x0248(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FName                                   ObjBackendName;                                    // 0x0250(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          CreativeMode;                                      // 0x0258(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_259[0x7];                                      // 0x0259(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDataTableRowHandle                    ObjectiveStat;                                     // 0x0260(0x0010)(Edit, BlueprintVisible, NoDestructor, ExposeOnSpawn)
	bool                                          IsLocallyValid;                                    // 0x0270(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_271[0x7];                                      // 0x0271(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             GenericSuccessSound;                               // 0x0278(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        GenericSuccessFX;                                  // 0x0280(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DelayBeforeGenericSuccessSoundAndFX;               // 0x0288(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         PlayerObjectiveCount;                              // 0x028C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 PlayerThatTriggeredObject;                         // 0x0290(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bTestQuest;                                        // 0x0298(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bIsQuestShared;                                    // 0x0299(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          PlaySuccessFX;                                     // 0x029A(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)

public:
	void ExecuteUbergraph_AthenaQuestActor_DF_GL1_Graffiti(int32 EntryPoint);
	void FoundEvent(class AFortPlayerController* PC);
	void TouchedActorInCreativeMode();
	void TellChildOfSuccess();
	void ObjectiveSuccessfullyCompleted(class AActor* PlayerWhoTriggeredObject);
	void QuestInitializedAndValid();
	void QuestSuccessfullyUpdated();
	void PlaylistLoaded(class FName PlaylistName, const struct FGameplayTagContainer& PlaylistContextTags);
	void TouchedQuestActor(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void ReceiveBeginPlay();
	void OnRep_ShoppingCartThatTriggered();
	void CheckShouldShowLocally(bool* ShouldShowLocally);
	void OnRep_PlaySuccessFX();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaQuestActor_DF_GL1_Graffiti_C">();
	}
	static class AAthenaQuestActor_DF_GL1_Graffiti_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAthenaQuestActor_DF_GL1_Graffiti_C>();
	}
};
static_assert(alignof(AAthenaQuestActor_DF_GL1_Graffiti_C) == 0x000008, "Wrong alignment on AAthenaQuestActor_DF_GL1_Graffiti_C");
static_assert(sizeof(AAthenaQuestActor_DF_GL1_Graffiti_C) == 0x0002A0, "Wrong size on AAthenaQuestActor_DF_GL1_Graffiti_C");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, UberGraphFrame) == 0x000220, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, P_Athena_QuestItem_PickupSuccess) == 0x000228, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::P_Athena_QuestItem_PickupSuccess' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, Athena_CollectHiddenStarReward_Cue) == 0x000230, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::Athena_CollectHiddenStarReward_Cue' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, TouchCapsule) == 0x000238, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::TouchCapsule' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, DefaultSceneRoot) == 0x000240, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, QuestItem) == 0x000248, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::QuestItem' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, ObjBackendName) == 0x000250, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::ObjBackendName' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, CreativeMode) == 0x000258, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::CreativeMode' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, ObjectiveStat) == 0x000260, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::ObjectiveStat' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, IsLocallyValid) == 0x000270, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::IsLocallyValid' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, GenericSuccessSound) == 0x000278, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::GenericSuccessSound' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, GenericSuccessFX) == 0x000280, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::GenericSuccessFX' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, DelayBeforeGenericSuccessSoundAndFX) == 0x000288, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::DelayBeforeGenericSuccessSoundAndFX' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, PlayerObjectiveCount) == 0x00028C, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::PlayerObjectiveCount' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, PlayerThatTriggeredObject) == 0x000290, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::PlayerThatTriggeredObject' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, bTestQuest) == 0x000298, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::bTestQuest' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, bIsQuestShared) == 0x000299, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::bIsQuestShared' has a wrong offset!");
static_assert(offsetof(AAthenaQuestActor_DF_GL1_Graffiti_C, PlaySuccessFX) == 0x00029A, "Member 'AAthenaQuestActor_DF_GL1_Graffiti_C::PlaySuccessFX' has a wrong offset!");

}

