#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaBroadcastGameTimeWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaBroadcastGameTimeWidget.AthenaBroadcastGameTimeWidget_C
// 0x0018 (0x0308 - 0x02F0)
class UAthenaBroadcastGameTimeWidget_C final : public UAthenaBroadcastGamePhaseWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Icon;                                              // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	EAthenaGamePhaseStep                          DesignTime_GamePhaseStep;                          // 0x0300(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bShowIcon;                                         // 0x0301(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_AthenaBroadcastGameTimeWidget(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void OnGamePhaseStepChanged(EAthenaGamePhaseStep GamePhaseStep);
	void SetIcon(EAthenaGamePhaseStep GamePhaseStep);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaBroadcastGameTimeWidget_C">();
	}
	static class UAthenaBroadcastGameTimeWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaBroadcastGameTimeWidget_C>();
	}
};
static_assert(alignof(UAthenaBroadcastGameTimeWidget_C) == 0x000008, "Wrong alignment on UAthenaBroadcastGameTimeWidget_C");
static_assert(sizeof(UAthenaBroadcastGameTimeWidget_C) == 0x000308, "Wrong size on UAthenaBroadcastGameTimeWidget_C");
static_assert(offsetof(UAthenaBroadcastGameTimeWidget_C, UberGraphFrame) == 0x0002F0, "Member 'UAthenaBroadcastGameTimeWidget_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastGameTimeWidget_C, Icon) == 0x0002F8, "Member 'UAthenaBroadcastGameTimeWidget_C::Icon' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastGameTimeWidget_C, DesignTime_GamePhaseStep) == 0x000300, "Member 'UAthenaBroadcastGameTimeWidget_C::DesignTime_GamePhaseStep' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastGameTimeWidget_C, bShowIcon) == 0x000301, "Member 'UAthenaBroadcastGameTimeWidget_C::bShowIcon' has a wrong offset!");

}

