#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaScoreAlert

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "Slate_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaScoreAlert.AthenaScoreAlert_C
// 0x01C8 (0x0490 - 0x02C8)
class UAthenaScoreAlert_C final : public UAthenaWinConditionMsgBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Exclamation;                                       // 0x02D0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Outro;                                             // 0x02D8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Intro;                                             // 0x02E0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UVerticalBox*                           Content;                                           // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ExclamationTextBlock;                              // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class URichTextBlock*                         MessageTextBlock;                                  // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         TestMessageType;                                   // 0x0300(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ContentOffset;                                     // 0x0304(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FHUDMessageData>                QueuedMessages;                                    // 0x0308(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	float                                         DefaultShowTime;                                   // 0x0318(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         IntroShowTime;                                     // 0x031C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHUDMessageData                        PreviousMessage;                                   // 0x0320(0x0058)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          TextStyleDataAsset;                                // 0x0378(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_379[0x7];                                      // 0x0379(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHUDMessageData                        CurrentMessage;                                    // 0x0380(0x0058)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FTimerHandle                           ShowTimeTimerHandle;                               // 0x03D8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FHUDMessageData                        NextMessage;                                       // 0x03E0(0x0058)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FTimerHandle                           OutroTimerHandle;                                  // 0x0438(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TMap<EWinConditionParentType, struct FWinConditionPlacementDataMapWrapper> Placements;                                        // 0x0440(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_AthenaScoreAlert(int32 EntryPoint);
	void BP_OnShowHUDMessage(const struct FHUDMessageData& MessageData);
	void BP_OnGameStateInitialized(class AFortGameState* GameState);
	void BP_OnMinigameEnded();
	void Construct();
	void PreConstruct(bool IsDesignTime);
	void PlaySoundFromType(const struct FHUDMessageData& MessageData);
	void UpdateContentTranslation(bool bShiftContentDown);
	void BindToGameStateEvents(class AFortGameState* GameState);
	void OnHideGameModeMessageRequest(EAthenaGameMsgType MessageType, bool bInstantHide, bool bClearQueue);
	void OnGameModeMessageRequest(const struct FAthenaGameMessageData& MessageData);
	void OnOutroAnimationFinished();
	void StartHideTimer();
	void ShouldPlayIntroAnimations(bool* bShouldPlay);
	void PlayIntroAnimations();
	void OnShowTimeExpired();
	void UpdateExclamationTextBlockColors(const class FText& Message);
	void DisplayMessage();
	void HandleMessageQueuing(bool* bMessageWasQueued);
	void TryToDisplayMessage(const struct FHUDMessageData& CurrentMessage_0);
	void FillInitialPositionData();
	void SetPlacement();
	void ConvertToHUDMessage(EHUDMessagePlacement Placement, ETextTransformPolicy Text_Transform_Policy, const struct FAthenaGameMessageData& AthenaGameMessageData, struct FHUDMessageData* HUDMessageData);
	void HUDMessageToText(const struct FHUDMessageData& HUDMessage, class FText* Text);
	void GetPlacementData(bool* bSuccess, struct FWinConditionPlacementData* PlacementData);
	void IsDesktop(bool* bReturnValue);
	TMap<EHUDMessagePlacement, struct FWinConditionPlacementData> GetAllPlacements(bool* bSuccess);

	void DoesWidgetHandleThisEnum(EAthenaGameMsgType MessageType, bool* bIsValid) const;
	void GetShowTimeInterval(const struct FHUDMessageData& MessageData, float* ShowTimeInterval) const;
	void IsMessageValidForViewTarget(const struct FHUDMessageData& Message, bool* bIsValid) const;
	void IsMessageValidForWidget(const struct FHUDMessageData& Message, bool* bIsValid) const;
	void GetRichTextStyleFromMessage(const class FText& Message, class FName* Style) const;
	void ShouldShowExclamation(bool* bShouldShow) const;
	void ShouldColorizeExclamationTextBlock(bool* bShouldColorize) const;
	void DoesTeamMatchViewTargetsTeam(int32 Team, bool* bDoesMatchViewTargetsTeam) const;
	void DoesViewTargetMatchTriggeringPlayer(class APlayerState* TriggeringPlayer, bool* bDoesMatch) const;
	void DoesViewTargetsTeamMatchTriggeringPlayersTeam(class APlayerState* TriggeringPlayer, bool* bDoesMatch) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaScoreAlert_C">();
	}
	static class UAthenaScoreAlert_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaScoreAlert_C>();
	}
};
static_assert(alignof(UAthenaScoreAlert_C) == 0x000008, "Wrong alignment on UAthenaScoreAlert_C");
static_assert(sizeof(UAthenaScoreAlert_C) == 0x000490, "Wrong size on UAthenaScoreAlert_C");
static_assert(offsetof(UAthenaScoreAlert_C, UberGraphFrame) == 0x0002C8, "Member 'UAthenaScoreAlert_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, Exclamation) == 0x0002D0, "Member 'UAthenaScoreAlert_C::Exclamation' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, Outro) == 0x0002D8, "Member 'UAthenaScoreAlert_C::Outro' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, Intro) == 0x0002E0, "Member 'UAthenaScoreAlert_C::Intro' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, Content) == 0x0002E8, "Member 'UAthenaScoreAlert_C::Content' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, ExclamationTextBlock) == 0x0002F0, "Member 'UAthenaScoreAlert_C::ExclamationTextBlock' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, MessageTextBlock) == 0x0002F8, "Member 'UAthenaScoreAlert_C::MessageTextBlock' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, TestMessageType) == 0x000300, "Member 'UAthenaScoreAlert_C::TestMessageType' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, ContentOffset) == 0x000304, "Member 'UAthenaScoreAlert_C::ContentOffset' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, QueuedMessages) == 0x000308, "Member 'UAthenaScoreAlert_C::QueuedMessages' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, DefaultShowTime) == 0x000318, "Member 'UAthenaScoreAlert_C::DefaultShowTime' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, IntroShowTime) == 0x00031C, "Member 'UAthenaScoreAlert_C::IntroShowTime' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, PreviousMessage) == 0x000320, "Member 'UAthenaScoreAlert_C::PreviousMessage' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, TextStyleDataAsset) == 0x000378, "Member 'UAthenaScoreAlert_C::TextStyleDataAsset' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, CurrentMessage) == 0x000380, "Member 'UAthenaScoreAlert_C::CurrentMessage' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, ShowTimeTimerHandle) == 0x0003D8, "Member 'UAthenaScoreAlert_C::ShowTimeTimerHandle' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, NextMessage) == 0x0003E0, "Member 'UAthenaScoreAlert_C::NextMessage' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, OutroTimerHandle) == 0x000438, "Member 'UAthenaScoreAlert_C::OutroTimerHandle' has a wrong offset!");
static_assert(offsetof(UAthenaScoreAlert_C, Placements) == 0x000440, "Member 'UAthenaScoreAlert_C::Placements' has a wrong offset!");

}

