#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_Prop_SilkyTanker

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function Athena_Prop_SilkyTanker.Athena_Prop_SilkyTanker_C.ExecuteUbergraph_Athena_Prop_SilkyTanker
// 0x0378 (0x0378 - 0x0000)
struct Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x0008(0x0010)(ConstParm, ReferenceParm, HasGetValueTypeHash)
	struct FRotator                               CallFunc_GetSocketRotation_ReturnValue;            // 0x0018(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_GetSocketLocation_ReturnValue;            // 0x0024(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x0038(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_Damage_1;                             // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  K2Node_Event_DamageTags_1;                         // 0x0058(0x0020)(ConstParm)
	struct FVector                                K2Node_Event_Momentum_1;                           // 0x0078(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_HitInfo_1;                            // 0x0084(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AController*                            K2Node_Event_InstigatedBy_1;                       // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_DamageCauser_1;                       // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEffectContextHandle           K2Node_Event_EffectContext_1;                      // 0x0120(0x0018)()
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0138(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x013C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_1;    // 0x0148(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_154[0x4];                                      // 0x0154(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0160(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0164(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0165(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_166[0x2];                                      // 0x0166(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_Damage;                               // 0x0168(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16C[0x4];                                      // 0x016C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  K2Node_Event_DamageTags;                           // 0x0170(0x0020)(ConstParm)
	struct FVector                                K2Node_Event_Momentum;                             // 0x0190(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_HitInfo;                              // 0x019C(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AFortPawn*                              K2Node_Event_InstigatedBy;                         // 0x0228(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_DamageCauser;                         // 0x0230(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEffectContextHandle           K2Node_Event_EffectContext;                        // 0x0238(0x0018)()
	float                                         CallFunc_BreakVector_X;                            // 0x0250(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x0254(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x0258(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RandomFloatInRangeFromStream_ReturnValue; // 0x025C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_2;    // 0x0260(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x026C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0278(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_284[0x4];                                      // 0x0284(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortAbilitySystemComponent*            CallFunc_GetFortAbilitySystemComponent_ReturnValue; // 0x0288(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_3;    // 0x0290(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x029C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetActorScale3D_ReturnValue;              // 0x02A8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_VSize_ReturnValue;                        // 0x02B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x02B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x02BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         CallFunc_SphereOverlapActors_OutActors;            // 0x02C0(0x0010)(ReferenceParm, HasGetValueTypeHash)
	bool                                          CallFunc_SphereOverlapActors_ReturnValue;          // 0x02D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D1[0x7];                                      // 0x02D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         CallFunc_SphereOverlapActors_OutActors_1;          // 0x02D8(0x0010)(ReferenceParm, HasGetValueTypeHash)
	bool                                          CallFunc_SphereOverlapActors_ReturnValue_1;        // 0x02E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2E9[0x7];                                      // 0x02E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_Array_Get_Item_1;                         // 0x02F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x02F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2F9[0x3];                                      // 0x02F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_AddUnique_ReturnValue;              // 0x02FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_Array_Get_Item_2;                         // 0x0300(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0308(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_AddUnique_ReturnValue_1;            // 0x030C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0310(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_311[0x3];                                      // 0x0311(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x0314(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0318(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_319[0x3];                                      // 0x0319(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x031C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetActorScale3D_ReturnValue_1;            // 0x0320(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_X_1;                          // 0x032C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y_1;                          // 0x0330(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z_1;                          // 0x0334(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPawn*                              K2Node_DynamicCast_AsFort_Pawn;                    // 0x0338(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0340(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_341[0x3];                                      // 0x0341(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_1;        // 0x0344(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAbilitySystemComponent*                CallFunc_GetAbilitySystemComponent_ReturnValue;    // 0x0348(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0350(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_351[0x3];                                      // 0x0351(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActiveGameplayEffectHandle            CallFunc_BP_FortApplyGameplayEffectToTarget_ReturnValue; // 0x0354(0x0008)(NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_2;        // 0x035C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue_3;        // 0x0360(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0364(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDecalComponent*                        CallFunc_SpawnDecalAtLocation_ReturnValue;         // 0x0370(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker) == 0x000008, "Wrong alignment on Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker");
static_assert(sizeof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker) == 0x000378, "Wrong size on Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, EntryPoint) == 0x000000, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::EntryPoint' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, Temp_object_Variable) == 0x000008, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_GetSocketRotation_ReturnValue) == 0x000018, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_GetSocketRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_GetSocketLocation_ReturnValue) == 0x000024, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_GetSocketLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, Temp_int_Loop_Counter_Variable) == 0x000030, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_SpawnEmitterAtLocation_ReturnValue) == 0x000038, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_SpawnEmitterAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Add_IntInt_ReturnValue) == 0x000040, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, Temp_int_Loop_Counter_Variable_1) == 0x000044, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Add_IntInt_ReturnValue_1) == 0x000048, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, Temp_int_Array_Index_Variable) == 0x00004C, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, Temp_int_Array_Index_Variable_1) == 0x000050, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_Event_Damage_1) == 0x000054, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_Event_Damage_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_Event_DamageTags_1) == 0x000058, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_Event_DamageTags_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_Event_Momentum_1) == 0x000078, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_Event_Momentum_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_Event_HitInfo_1) == 0x000084, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_Event_HitInfo_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_Event_InstigatedBy_1) == 0x000110, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_Event_InstigatedBy_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_Event_DamageCauser_1) == 0x000118, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_Event_DamageCauser_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_Event_EffectContext_1) == 0x000120, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_Event_EffectContext_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, Temp_int_Array_Index_Variable_2) == 0x000138, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x00013C, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_K2_GetComponentLocation_ReturnValue_1) == 0x000148, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_K2_GetComponentLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Array_Get_Item) == 0x000158, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Array_Length_ReturnValue) == 0x000160, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_IsValid_ReturnValue) == 0x000164, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Less_IntInt_ReturnValue) == 0x000165, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_Event_Damage) == 0x000168, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_Event_Damage' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_Event_DamageTags) == 0x000170, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_Event_DamageTags' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_Event_Momentum) == 0x000190, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_Event_Momentum' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_Event_HitInfo) == 0x00019C, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_Event_HitInfo' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_Event_InstigatedBy) == 0x000228, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_Event_InstigatedBy' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_Event_DamageCauser) == 0x000230, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_Event_DamageCauser' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_Event_EffectContext) == 0x000238, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_Event_EffectContext' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_BreakVector_X) == 0x000250, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_BreakVector_Y) == 0x000254, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_BreakVector_Z) == 0x000258, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_RandomFloatInRangeFromStream_ReturnValue) == 0x00025C, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_RandomFloatInRangeFromStream_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_K2_GetComponentLocation_ReturnValue_2) == 0x000260, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_K2_GetComponentLocation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_MakeRotator_ReturnValue) == 0x00026C, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Subtract_VectorVector_ReturnValue) == 0x000278, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_GetFortAbilitySystemComponent_ReturnValue) == 0x000288, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_GetFortAbilitySystemComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_K2_GetComponentLocation_ReturnValue_3) == 0x000290, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_K2_GetComponentLocation_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Add_VectorVector_ReturnValue) == 0x00029C, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_GetActorScale3D_ReturnValue) == 0x0002A8, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_GetActorScale3D_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_VSize_ReturnValue) == 0x0002B4, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_VSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, Temp_int_Loop_Counter_Variable_2) == 0x0002B8, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x0002BC, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_SphereOverlapActors_OutActors) == 0x0002C0, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_SphereOverlapActors_OutActors' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_SphereOverlapActors_ReturnValue) == 0x0002D0, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_SphereOverlapActors_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_SphereOverlapActors_OutActors_1) == 0x0002D8, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_SphereOverlapActors_OutActors_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_SphereOverlapActors_ReturnValue_1) == 0x0002E8, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_SphereOverlapActors_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Array_Get_Item_1) == 0x0002F0, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_BooleanOR_ReturnValue) == 0x0002F8, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Array_AddUnique_ReturnValue) == 0x0002FC, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Array_AddUnique_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Array_Get_Item_2) == 0x000300, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Array_Length_ReturnValue_1) == 0x000308, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Array_AddUnique_ReturnValue_1) == 0x00030C, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Array_AddUnique_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Less_IntInt_ReturnValue_1) == 0x000310, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Array_Length_ReturnValue_2) == 0x000314, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Less_IntInt_ReturnValue_2) == 0x000318, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Add_IntInt_ReturnValue_2) == 0x00031C, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_GetActorScale3D_ReturnValue_1) == 0x000320, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_GetActorScale3D_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_BreakVector_X_1) == 0x00032C, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_BreakVector_Y_1) == 0x000330, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_BreakVector_Z_1) == 0x000334, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_DynamicCast_AsFort_Pawn) == 0x000338, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_DynamicCast_AsFort_Pawn' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, K2Node_DynamicCast_bSuccess) == 0x000340, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Multiply_FloatFloat_ReturnValue_1) == 0x000344, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Multiply_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_GetAbilitySystemComponent_ReturnValue) == 0x000348, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_GetAbilitySystemComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_IsValid_ReturnValue_1) == 0x000350, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_BP_FortApplyGameplayEffectToTarget_ReturnValue) == 0x000354, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_BP_FortApplyGameplayEffectToTarget_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Multiply_FloatFloat_ReturnValue_2) == 0x00035C, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Multiply_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_Multiply_FloatFloat_ReturnValue_3) == 0x000360, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_Multiply_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_MakeVector_ReturnValue) == 0x000364, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker, CallFunc_SpawnDecalAtLocation_ReturnValue) == 0x000370, "Member 'Athena_Prop_SilkyTanker_C_ExecuteUbergraph_Athena_Prop_SilkyTanker::CallFunc_SpawnDecalAtLocation_ReturnValue' has a wrong offset!");

// Function Athena_Prop_SilkyTanker.Athena_Prop_SilkyTanker_C.OnDeathPlayEffects
// 0x00E8 (0x00E8 - 0x0000)
struct Athena_Prop_SilkyTanker_C_OnDeathPlayEffects final
{
public:
	float                                         Damage;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  DamageTags;                                        // 0x0008(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FVector                                Momentum;                                          // 0x0028(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             HitInfo;                                           // 0x0034(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AFortPawn*                              InstigatedBy;                                      // 0x00C0(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 DamageCauser;                                      // 0x00C8(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEffectContextHandle           EffectContext;                                     // 0x00D0(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(Athena_Prop_SilkyTanker_C_OnDeathPlayEffects) == 0x000008, "Wrong alignment on Athena_Prop_SilkyTanker_C_OnDeathPlayEffects");
static_assert(sizeof(Athena_Prop_SilkyTanker_C_OnDeathPlayEffects) == 0x0000E8, "Wrong size on Athena_Prop_SilkyTanker_C_OnDeathPlayEffects");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_OnDeathPlayEffects, Damage) == 0x000000, "Member 'Athena_Prop_SilkyTanker_C_OnDeathPlayEffects::Damage' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_OnDeathPlayEffects, DamageTags) == 0x000008, "Member 'Athena_Prop_SilkyTanker_C_OnDeathPlayEffects::DamageTags' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_OnDeathPlayEffects, Momentum) == 0x000028, "Member 'Athena_Prop_SilkyTanker_C_OnDeathPlayEffects::Momentum' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_OnDeathPlayEffects, HitInfo) == 0x000034, "Member 'Athena_Prop_SilkyTanker_C_OnDeathPlayEffects::HitInfo' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_OnDeathPlayEffects, InstigatedBy) == 0x0000C0, "Member 'Athena_Prop_SilkyTanker_C_OnDeathPlayEffects::InstigatedBy' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_OnDeathPlayEffects, DamageCauser) == 0x0000C8, "Member 'Athena_Prop_SilkyTanker_C_OnDeathPlayEffects::DamageCauser' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_OnDeathPlayEffects, EffectContext) == 0x0000D0, "Member 'Athena_Prop_SilkyTanker_C_OnDeathPlayEffects::EffectContext' has a wrong offset!");

// Function Athena_Prop_SilkyTanker.Athena_Prop_SilkyTanker_C.OnDeathServer
// 0x00E8 (0x00E8 - 0x0000)
struct Athena_Prop_SilkyTanker_C_OnDeathServer final
{
public:
	float                                         Damage;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  DamageTags;                                        // 0x0008(0x0020)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FVector                                Momentum;                                          // 0x0028(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             HitInfo;                                           // 0x0034(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AController*                            InstigatedBy;                                      // 0x00C0(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 DamageCauser;                                      // 0x00C8(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEffectContextHandle           EffectContext;                                     // 0x00D0(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(Athena_Prop_SilkyTanker_C_OnDeathServer) == 0x000008, "Wrong alignment on Athena_Prop_SilkyTanker_C_OnDeathServer");
static_assert(sizeof(Athena_Prop_SilkyTanker_C_OnDeathServer) == 0x0000E8, "Wrong size on Athena_Prop_SilkyTanker_C_OnDeathServer");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_OnDeathServer, Damage) == 0x000000, "Member 'Athena_Prop_SilkyTanker_C_OnDeathServer::Damage' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_OnDeathServer, DamageTags) == 0x000008, "Member 'Athena_Prop_SilkyTanker_C_OnDeathServer::DamageTags' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_OnDeathServer, Momentum) == 0x000028, "Member 'Athena_Prop_SilkyTanker_C_OnDeathServer::Momentum' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_OnDeathServer, HitInfo) == 0x000034, "Member 'Athena_Prop_SilkyTanker_C_OnDeathServer::HitInfo' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_OnDeathServer, InstigatedBy) == 0x0000C0, "Member 'Athena_Prop_SilkyTanker_C_OnDeathServer::InstigatedBy' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_OnDeathServer, DamageCauser) == 0x0000C8, "Member 'Athena_Prop_SilkyTanker_C_OnDeathServer::DamageCauser' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_OnDeathServer, EffectContext) == 0x0000D0, "Member 'Athena_Prop_SilkyTanker_C_OnDeathServer::EffectContext' has a wrong offset!");

// Function Athena_Prop_SilkyTanker.Athena_Prop_SilkyTanker_C.ShouldDie
// 0x0020 (0x0020 - 0x0000)
struct Athena_Prop_SilkyTanker_C_ShouldDie final
{
public:
	float                                         Damage;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            EventInstigator;                                   // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 DamageCauser;                                      // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0018(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Athena_Prop_SilkyTanker_C_ShouldDie) == 0x000008, "Wrong alignment on Athena_Prop_SilkyTanker_C_ShouldDie");
static_assert(sizeof(Athena_Prop_SilkyTanker_C_ShouldDie) == 0x000020, "Wrong size on Athena_Prop_SilkyTanker_C_ShouldDie");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ShouldDie, Damage) == 0x000000, "Member 'Athena_Prop_SilkyTanker_C_ShouldDie::Damage' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ShouldDie, EventInstigator) == 0x000008, "Member 'Athena_Prop_SilkyTanker_C_ShouldDie::EventInstigator' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ShouldDie, DamageCauser) == 0x000010, "Member 'Athena_Prop_SilkyTanker_C_ShouldDie::DamageCauser' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ShouldDie, ReturnValue) == 0x000018, "Member 'Athena_Prop_SilkyTanker_C_ShouldDie::ReturnValue' has a wrong offset!");

// Function Athena_Prop_SilkyTanker.Athena_Prop_SilkyTanker_C.ApplyWaterIfCurieEnabled
// 0x00B0 (0x00B0 - 0x0000)
struct Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled final
{
public:
	class AActor*                                 Instigator_0;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Target;                                            // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0010(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_MakeHitResult_ReturnValue;                // 0x0020(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_IsCurieActive_ReturnValue;                // 0x00AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x00AD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled) == 0x000008, "Wrong alignment on Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled");
static_assert(sizeof(Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled) == 0x0000B0, "Wrong size on Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled, Instigator_0) == 0x000000, "Member 'Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled::Instigator_0' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled, Target) == 0x000008, "Member 'Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled::Target' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000010, "Member 'Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled, CallFunc_IsValid_ReturnValue) == 0x00001C, "Member 'Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled, CallFunc_MakeHitResult_ReturnValue) == 0x000020, "Member 'Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled::CallFunc_MakeHitResult_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled, CallFunc_IsCurieActive_ReturnValue) == 0x0000AC, "Member 'Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled::CallFunc_IsCurieActive_ReturnValue' has a wrong offset!");
static_assert(offsetof(Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled, CallFunc_IsDedicatedServer_ReturnValue) == 0x0000AD, "Member 'Athena_Prop_SilkyTanker_C_ApplyWaterIfCurieEnabled::CallFunc_IsDedicatedServer_ReturnValue' has a wrong offset!");

}

