#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_Prop_Office_Cubicles_01

#include "Basic.hpp"

#include "Athena_Prop_ParentBuildingContainerBlueprint_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_Prop_Office_Cubicles_01.Athena_Prop_Office_Cubicles_01_C
// 0x0010 (0x0C98 - 0x0C88)
class AAthena_Prop_Office_Cubicles_01_C final : public AAthena_Prop_ParentBuildingContainerBlueprint_C
{
public:
	class USpotLightComponent*                    SpotLight1;                                        // 0x0C88(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight;                                         // 0x0C90(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Athena_Prop_Office_Cubicles_01_C">();
	}
	static class AAthena_Prop_Office_Cubicles_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAthena_Prop_Office_Cubicles_01_C>();
	}
};
static_assert(alignof(AAthena_Prop_Office_Cubicles_01_C) == 0x000008, "Wrong alignment on AAthena_Prop_Office_Cubicles_01_C");
static_assert(sizeof(AAthena_Prop_Office_Cubicles_01_C) == 0x000C98, "Wrong size on AAthena_Prop_Office_Cubicles_01_C");
static_assert(offsetof(AAthena_Prop_Office_Cubicles_01_C, SpotLight1) == 0x000C88, "Member 'AAthena_Prop_Office_Cubicles_01_C::SpotLight1' has a wrong offset!");
static_assert(offsetof(AAthena_Prop_Office_Cubicles_01_C, SpotLight) == 0x000C90, "Member 'AAthena_Prop_Office_Cubicles_01_C::SpotLight' has a wrong offset!");

}

