#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_Prop_DanceClub_Couch

#include "Basic.hpp"

#include "Couch_parent_Container_Athena_NoSearch_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_Prop_DanceClub_Couch.Athena_Prop_DanceClub_Couch_C
// 0x0000 (0x0D80 - 0x0D80)
class AAthena_Prop_DanceClub_Couch_C final : public ACouch_parent_Container_Athena_NoSearch_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Athena_Prop_DanceClub_Couch_C">();
	}
	static class AAthena_Prop_DanceClub_Couch_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAthena_Prop_DanceClub_Couch_C>();
	}
};
static_assert(alignof(AAthena_Prop_DanceClub_Couch_C) == 0x000008, "Wrong alignment on AAthena_Prop_DanceClub_Couch_C");
static_assert(sizeof(AAthena_Prop_DanceClub_Couch_C) == 0x000D80, "Wrong size on AAthena_Prop_DanceClub_Couch_C");

}

