#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaBroadcastNameplate

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaBroadcastNameplate.AthenaBroadcastNameplate_C
// 0x0088 (0x03A8 - 0x0320)
class UAthenaBroadcastNameplate_C final : public UAthenaSpectatorNameplateBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0320(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonBorder*                          Background;                                        // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Chevron;                                           // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaSpectatorHitPointBar_C*          HealthBar;                                         // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               HealthBarSB;                                       // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       PlayerName;                                        // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaSpectatorHitPointBar_C*          ShieldBar;                                         // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               ShieldBarSB;                                       // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox;                                           // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          TeamColor;                                         // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          TeamColor2;                                        // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               TeamColor2SB;                                      // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       TeamNumber;                                        // 0x0380(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               TeamSB;                                            // 0x0388(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UAthenaSpectatorHitPointBar_C*          VehicleHealthBar;                                  // 0x0390(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               VehicleHealthSB;                                   // 0x0398(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	float                                         HitPointBarFarHeight;                              // 0x03A0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          InVehicle;                                         // 0x03A4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	EAthenaSpectatorNameplateDetailState          DesignTime_DetailState;                            // 0x03A5(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DesignTime_InVehicle;                              // 0x03A6(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          ShouldColorArrow;                                  // 0x03A7(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_AthenaBroadcastNameplate(int32 EntryPoint);
	void OnVehicleStateChanged(class AActor* NewVehicle, class AActor* OldVehicle);
	void SetArrowTeamColorVisible(bool bArrowTeamColorVisible);
	void SetTeamColorVisible(bool bTeamColorVisible);
	void SetSquadIdVisibility(bool bSquadIdVisible);
	void OnDetailStateChanged(EAthenaSpectatorNameplateDetailState NewDetailState);
	void OnSquadIdChanged(class UAthenaRemotePlayerViewData* InPlayerData, uint8 InSquadId);
	void OnPlayerNameChanged(class UAthenaRemotePlayerViewData* InPlayerData, const class FString& InPlayerName);
	void OnTeamColorChanged(class UAthenaRemotePlayerViewData* InPlayerData, const struct FLinearColor& InTeamColor);
	void OnDistanceStateChanged(EAthenaSpectatorNameplateDistanceState NewDistanceState);
	void OnPlayerDataSet(class UAthenaRemotePlayerViewData* InPlayerData);
	void PreConstruct(bool IsDesignTime);
	void UpdateBackgroundRenderScale();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaBroadcastNameplate_C">();
	}
	static class UAthenaBroadcastNameplate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaBroadcastNameplate_C>();
	}
};
static_assert(alignof(UAthenaBroadcastNameplate_C) == 0x000008, "Wrong alignment on UAthenaBroadcastNameplate_C");
static_assert(sizeof(UAthenaBroadcastNameplate_C) == 0x0003A8, "Wrong size on UAthenaBroadcastNameplate_C");
static_assert(offsetof(UAthenaBroadcastNameplate_C, UberGraphFrame) == 0x000320, "Member 'UAthenaBroadcastNameplate_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, Background) == 0x000328, "Member 'UAthenaBroadcastNameplate_C::Background' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, Chevron) == 0x000330, "Member 'UAthenaBroadcastNameplate_C::Chevron' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, HealthBar) == 0x000338, "Member 'UAthenaBroadcastNameplate_C::HealthBar' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, HealthBarSB) == 0x000340, "Member 'UAthenaBroadcastNameplate_C::HealthBarSB' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, PlayerName) == 0x000348, "Member 'UAthenaBroadcastNameplate_C::PlayerName' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, ShieldBar) == 0x000350, "Member 'UAthenaBroadcastNameplate_C::ShieldBar' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, ShieldBarSB) == 0x000358, "Member 'UAthenaBroadcastNameplate_C::ShieldBarSB' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, SizeBox) == 0x000360, "Member 'UAthenaBroadcastNameplate_C::SizeBox' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, TeamColor) == 0x000368, "Member 'UAthenaBroadcastNameplate_C::TeamColor' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, TeamColor2) == 0x000370, "Member 'UAthenaBroadcastNameplate_C::TeamColor2' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, TeamColor2SB) == 0x000378, "Member 'UAthenaBroadcastNameplate_C::TeamColor2SB' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, TeamNumber) == 0x000380, "Member 'UAthenaBroadcastNameplate_C::TeamNumber' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, TeamSB) == 0x000388, "Member 'UAthenaBroadcastNameplate_C::TeamSB' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, VehicleHealthBar) == 0x000390, "Member 'UAthenaBroadcastNameplate_C::VehicleHealthBar' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, VehicleHealthSB) == 0x000398, "Member 'UAthenaBroadcastNameplate_C::VehicleHealthSB' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, HitPointBarFarHeight) == 0x0003A0, "Member 'UAthenaBroadcastNameplate_C::HitPointBarFarHeight' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, InVehicle) == 0x0003A4, "Member 'UAthenaBroadcastNameplate_C::InVehicle' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, DesignTime_DetailState) == 0x0003A5, "Member 'UAthenaBroadcastNameplate_C::DesignTime_DetailState' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, DesignTime_InVehicle) == 0x0003A6, "Member 'UAthenaBroadcastNameplate_C::DesignTime_InVehicle' has a wrong offset!");
static_assert(offsetof(UAthenaBroadcastNameplate_C, ShouldColorArrow) == 0x0003A7, "Member 'UAthenaBroadcastNameplate_C::ShouldColorArrow' has a wrong offset!");

}

