#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Athena_VendingMachine

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Athena_VendingMachine.B_Athena_VendingMachine_C
// 0x01D0 (0x0B70 - 0x09A0)
class AB_Athena_VendingMachine_C final : public ABuildingItemCollectorActor
{
public:
	uint8                                         Pad_998[0x8];                                      // 0x0998(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x09A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UParticleSystemComponent*               P_Destroyed_Effect_Vending;                        // 0x09A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight;                                         // 0x09B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UForceFeedbackComponent*                ForceFeedbackFail;                                 // 0x09B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UForceFeedbackComponent*                ForceFeedbackSuccess;                              // 0x09C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        VendingMachine_Ambient;                            // 0x09C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               P_Loot_Effect_Vending;                             // 0x09D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_VendingMachineQuest;                            // 0x09D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x09E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         VendWobble_Flash_70FB301E43A001CE1340FE8051EE86B5; // 0x09E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         VendWobble_WobbleTime_70FB301E43A001CE1340FE8051EE86B5; // 0x09EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            VendWobble__Direction_70FB301E43A001CE1340FE8051EE86B5; // 0x09F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9F1[0x7];                                      // 0x09F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     VendWobble;                                        // 0x09F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SwitchHitch_Slide_A93D31CA462BFD95FDDD9E8A0BE99DA5; // 0x0A00(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SwitchHitch_Flash_A93D31CA462BFD95FDDD9E8A0BE99DA5; // 0x0A04(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SwitchHitch_Wobble_A93D31CA462BFD95FDDD9E8A0BE99DA5; // 0x0A08(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            SwitchHitch__Direction_A93D31CA462BFD95FDDD9E8A0BE99DA5; // 0x0A0C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A0D[0x3];                                      // 0x0A0D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     SwitchHitch;                                       // 0x0A10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               MonitorMat;                                        // 0x0A18(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               MetalMat;                                          // 0x0A20(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CurrentCaptureCount;                               // 0x0A28(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A2C[0x4];                                      // 0x0A2C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Vend_String;                                       // 0x0A30(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class USoundBase*                             SearchSound;                                       // 0x0A48(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             VendFailedSound;                                   // 0x0A50(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             CycleSound;                                        // 0x0A58(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CostAmount;                                        // 0x0A60(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A64[0x4];                                      // 0x0A64(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture*                               MaterialType;                                      // 0x0A68(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Vend_Succeeded_Sound;                              // 0x0A70(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          VendSuccess;                                       // 0x0A78(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          WasHit;                                            // 0x0A79(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A7A[0x2];                                      // 0x0A7A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CycleSoundVolume;                                  // 0x0A7C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FCurveTableRowHandle                   TossOnGroundSetting;                               // 0x0A80(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class FText                                   Wood_String;                                       // 0x0A90(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   Stone_String;                                      // 0x0AA8(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   Metal_String;                                      // 0x0AC0(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	EFortRarity                                   OverrideVendingMachineRarity;                      // 0x0AD8(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, SaveGame, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AD9[0x7];                                      // 0x0AD9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             Ambient_SoundCue;                                  // 0x0AE0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   Free_String;                                       // 0x0AE8(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class USoundBase*                             DestroyedSound;                                    // 0x0B00(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         MaxItemsToSpawn;                                   // 0x0B08(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         ItemsAreFree;                                      // 0x0B30(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          ItemsAreFreeCached;                                // 0x0B58(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B59[0x3];                                      // 0x0B59(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         SpawnedItemCount;                                  // 0x0B5C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MaxItemsToSpawnCached;                             // 0x0B60(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B64[0x4];                                      // 0x0B64(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPawn*                              InteractingPawn;                                   // 0x0B68(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SetRarityColors(const struct FLinearColor& Color);
	void SwitchHitch__FinishedFunc();
	void SwitchHitch__UpdateFunc();
	void VendWobble__FinishedFunc();
	void VendWobble__UpdateFunc();
	void VendWobble__Start_FF_Time__EventFunc();
	void OnReady_21959F7346995C2CA1D67DB9455B627D(class AFortGameStateAthena* GameState, const class UFortPlaylist* Playlist, const struct FGameplayTagContainer& PlaylistContextTags);
	void UpdateCollectorsActiveItem(int32 StartingSeedValue, class UFortWorldItemDefinition* InputItem, class UTexture* InputTexture, int32 CurrentGoal, int32 CurrentCollectedAmount, int32 CurrentCaptureCount_0, class UTexture* OutputTexture);
	void BlueprintOnInteract(const class AFortPawn* InteractingPawn_0, const EInteractionBeingAttempted InteractionBeingAttempted);
	void BlueprintOnBeginInteract(const class AFortPawn* InteractingPawn_0, const EInteractionBeingAttempted InteractionBeingAttempted, const ETInteractionType InteractionType);
	void PlayVendFX();
	void ReceiveBeginPlay();
	void PlayVendFailFX();
	void OnForcedCycle();
	void DoVendDeath();
	void PickupSpawned_Bind();
	void ExecuteUbergraph_B_Athena_VendingMachine(int32 EntryPoint);

	bool GetOverrideRarity(EFortRarity* Rarity) const;
	class FText BlueprintGetInteractionString(const class AFortPawn* InteractingPawn_0, const EInteractionBeingAttempted InteractionBeingAttempted) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Athena_VendingMachine_C">();
	}
	static class AB_Athena_VendingMachine_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Athena_VendingMachine_C>();
	}
};
static_assert(alignof(AB_Athena_VendingMachine_C) == 0x000010, "Wrong alignment on AB_Athena_VendingMachine_C");
static_assert(sizeof(AB_Athena_VendingMachine_C) == 0x000B70, "Wrong size on AB_Athena_VendingMachine_C");
static_assert(offsetof(AB_Athena_VendingMachine_C, UberGraphFrame) == 0x0009A0, "Member 'AB_Athena_VendingMachine_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, P_Destroyed_Effect_Vending) == 0x0009A8, "Member 'AB_Athena_VendingMachine_C::P_Destroyed_Effect_Vending' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, SpotLight) == 0x0009B0, "Member 'AB_Athena_VendingMachine_C::SpotLight' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, ForceFeedbackFail) == 0x0009B8, "Member 'AB_Athena_VendingMachine_C::ForceFeedbackFail' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, ForceFeedbackSuccess) == 0x0009C0, "Member 'AB_Athena_VendingMachine_C::ForceFeedbackSuccess' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, VendingMachine_Ambient) == 0x0009C8, "Member 'AB_Athena_VendingMachine_C::VendingMachine_Ambient' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, P_Loot_Effect_Vending) == 0x0009D0, "Member 'AB_Athena_VendingMachine_C::P_Loot_Effect_Vending' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, SM_VendingMachineQuest) == 0x0009D8, "Member 'AB_Athena_VendingMachine_C::SM_VendingMachineQuest' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, DefaultSceneRoot) == 0x0009E0, "Member 'AB_Athena_VendingMachine_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, VendWobble_Flash_70FB301E43A001CE1340FE8051EE86B5) == 0x0009E8, "Member 'AB_Athena_VendingMachine_C::VendWobble_Flash_70FB301E43A001CE1340FE8051EE86B5' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, VendWobble_WobbleTime_70FB301E43A001CE1340FE8051EE86B5) == 0x0009EC, "Member 'AB_Athena_VendingMachine_C::VendWobble_WobbleTime_70FB301E43A001CE1340FE8051EE86B5' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, VendWobble__Direction_70FB301E43A001CE1340FE8051EE86B5) == 0x0009F0, "Member 'AB_Athena_VendingMachine_C::VendWobble__Direction_70FB301E43A001CE1340FE8051EE86B5' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, VendWobble) == 0x0009F8, "Member 'AB_Athena_VendingMachine_C::VendWobble' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, SwitchHitch_Slide_A93D31CA462BFD95FDDD9E8A0BE99DA5) == 0x000A00, "Member 'AB_Athena_VendingMachine_C::SwitchHitch_Slide_A93D31CA462BFD95FDDD9E8A0BE99DA5' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, SwitchHitch_Flash_A93D31CA462BFD95FDDD9E8A0BE99DA5) == 0x000A04, "Member 'AB_Athena_VendingMachine_C::SwitchHitch_Flash_A93D31CA462BFD95FDDD9E8A0BE99DA5' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, SwitchHitch_Wobble_A93D31CA462BFD95FDDD9E8A0BE99DA5) == 0x000A08, "Member 'AB_Athena_VendingMachine_C::SwitchHitch_Wobble_A93D31CA462BFD95FDDD9E8A0BE99DA5' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, SwitchHitch__Direction_A93D31CA462BFD95FDDD9E8A0BE99DA5) == 0x000A0C, "Member 'AB_Athena_VendingMachine_C::SwitchHitch__Direction_A93D31CA462BFD95FDDD9E8A0BE99DA5' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, SwitchHitch) == 0x000A10, "Member 'AB_Athena_VendingMachine_C::SwitchHitch' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, MonitorMat) == 0x000A18, "Member 'AB_Athena_VendingMachine_C::MonitorMat' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, MetalMat) == 0x000A20, "Member 'AB_Athena_VendingMachine_C::MetalMat' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, CurrentCaptureCount) == 0x000A28, "Member 'AB_Athena_VendingMachine_C::CurrentCaptureCount' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, Vend_String) == 0x000A30, "Member 'AB_Athena_VendingMachine_C::Vend_String' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, SearchSound) == 0x000A48, "Member 'AB_Athena_VendingMachine_C::SearchSound' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, VendFailedSound) == 0x000A50, "Member 'AB_Athena_VendingMachine_C::VendFailedSound' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, CycleSound) == 0x000A58, "Member 'AB_Athena_VendingMachine_C::CycleSound' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, CostAmount) == 0x000A60, "Member 'AB_Athena_VendingMachine_C::CostAmount' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, MaterialType) == 0x000A68, "Member 'AB_Athena_VendingMachine_C::MaterialType' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, Vend_Succeeded_Sound) == 0x000A70, "Member 'AB_Athena_VendingMachine_C::Vend_Succeeded_Sound' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, VendSuccess) == 0x000A78, "Member 'AB_Athena_VendingMachine_C::VendSuccess' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, WasHit) == 0x000A79, "Member 'AB_Athena_VendingMachine_C::WasHit' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, CycleSoundVolume) == 0x000A7C, "Member 'AB_Athena_VendingMachine_C::CycleSoundVolume' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, TossOnGroundSetting) == 0x000A80, "Member 'AB_Athena_VendingMachine_C::TossOnGroundSetting' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, Wood_String) == 0x000A90, "Member 'AB_Athena_VendingMachine_C::Wood_String' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, Stone_String) == 0x000AA8, "Member 'AB_Athena_VendingMachine_C::Stone_String' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, Metal_String) == 0x000AC0, "Member 'AB_Athena_VendingMachine_C::Metal_String' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, OverrideVendingMachineRarity) == 0x000AD8, "Member 'AB_Athena_VendingMachine_C::OverrideVendingMachineRarity' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, Ambient_SoundCue) == 0x000AE0, "Member 'AB_Athena_VendingMachine_C::Ambient_SoundCue' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, Free_String) == 0x000AE8, "Member 'AB_Athena_VendingMachine_C::Free_String' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, DestroyedSound) == 0x000B00, "Member 'AB_Athena_VendingMachine_C::DestroyedSound' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, MaxItemsToSpawn) == 0x000B08, "Member 'AB_Athena_VendingMachine_C::MaxItemsToSpawn' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, ItemsAreFree) == 0x000B30, "Member 'AB_Athena_VendingMachine_C::ItemsAreFree' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, ItemsAreFreeCached) == 0x000B58, "Member 'AB_Athena_VendingMachine_C::ItemsAreFreeCached' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, SpawnedItemCount) == 0x000B5C, "Member 'AB_Athena_VendingMachine_C::SpawnedItemCount' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, MaxItemsToSpawnCached) == 0x000B60, "Member 'AB_Athena_VendingMachine_C::MaxItemsToSpawnCached' has a wrong offset!");
static_assert(offsetof(AB_Athena_VendingMachine_C, InteractingPawn) == 0x000B68, "Member 'AB_Athena_VendingMachine_C::InteractingPawn' has a wrong offset!");

}

