#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Athena_S15Plugin_GenericQuestActor_Doggo_BuriedGnome

#include "Basic.hpp"

#include "B_Athena_S15Plugin_GenericQuestActor_Child_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Athena_S15Plugin_GenericQuestActor_Doggo_BuriedGnome.B_Athena_S15Plugin_GenericQuestActor_Doggo_BuriedGnome_C
// 0x0000 (0x0C10 - 0x0C10)
class AB_Athena_S15Plugin_GenericQuestActor_Doggo_BuriedGnome_C final : public AB_Athena_S15Plugin_GenericQuestActor_Child_C
{
public:
	uint8                                         Pad_C06[0x2];                                      // 0x0C06(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMeshComponent*                   SM_DirtMound;                                      // 0x0C08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Athena_S15Plugin_GenericQuestActor_Doggo_BuriedGnome_C">();
	}
	static class AB_Athena_S15Plugin_GenericQuestActor_Doggo_BuriedGnome_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Athena_S15Plugin_GenericQuestActor_Doggo_BuriedGnome_C>();
	}
};
static_assert(alignof(AB_Athena_S15Plugin_GenericQuestActor_Doggo_BuriedGnome_C) == 0x000010, "Wrong alignment on AB_Athena_S15Plugin_GenericQuestActor_Doggo_BuriedGnome_C");
static_assert(sizeof(AB_Athena_S15Plugin_GenericQuestActor_Doggo_BuriedGnome_C) == 0x000C10, "Wrong size on AB_Athena_S15Plugin_GenericQuestActor_Doggo_BuriedGnome_C");
static_assert(offsetof(AB_Athena_S15Plugin_GenericQuestActor_Doggo_BuriedGnome_C, SM_DirtMound) == 0x000C08, "Member 'AB_Athena_S15Plugin_GenericQuestActor_Doggo_BuriedGnome_C::SM_DirtMound' has a wrong offset!");

}

