#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Athena_S15Plugin_GenericQuestActor_Child

#include "Basic.hpp"

#include "B_Athena_S15GenericQuestActor_Parent_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Athena_S15Plugin_GenericQuestActor_Child.B_Athena_S15Plugin_GenericQuestActor_Child_C
// 0x0000 (0x0C10 - 0x0C10)
#pragma pack(push, 0x1)
class alignas(0x10) AB_Athena_S15Plugin_GenericQuestActor_Child_C : public AB_Athena_S15GenericQuestActor_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Athena_S15Plugin_GenericQuestActor_Child_C">();
	}
	static class AB_Athena_S15Plugin_GenericQuestActor_Child_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Athena_S15Plugin_GenericQuestActor_Child_C>();
	}
};
#pragma pack(pop)
static_assert(alignof(AB_Athena_S15Plugin_GenericQuestActor_Child_C) == 0x000010, "Wrong alignment on AB_Athena_S15Plugin_GenericQuestActor_Child_C");
static_assert(sizeof(AB_Athena_S15Plugin_GenericQuestActor_Child_C) == 0x000C10, "Wrong size on AB_Athena_S15Plugin_GenericQuestActor_Child_C");

}

