#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BGA_Quest_FlamingRing

#include "Basic.hpp"

#include "BGA_Quest_FlamingRing_0_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BGA_Quest_FlamingRing.BGA_Quest_FlamingRing_C
// 0x0000 (0x0890 - 0x0890)
class BGA_Quest_FlamingRing::ABGA_Quest_FlamingRing_C final : public BGA_Quest_FlamingRing_0::ABGA_Quest_FlamingRing_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BlueprintGeneratedClass BGA_Quest_FlamingRing.BGA_Quest_FlamingRing_C", true, "BGA_Quest_FlamingRing_C">();
	}
	static class BGA_Quest_FlamingRing::ABGA_Quest_FlamingRing_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<BGA_Quest_FlamingRing::ABGA_Quest_FlamingRing_C>();
	}
};
static_assert(alignof(BGA_Quest_FlamingRing::ABGA_Quest_FlamingRing_C) == 0x000008, "Wrong alignment on BGA_Quest_FlamingRing::ABGA_Quest_FlamingRing_C");
static_assert(sizeof(BGA_Quest_FlamingRing::ABGA_Quest_FlamingRing_C) == 0x000890, "Wrong size on BGA_Quest_FlamingRing::ABGA_Quest_FlamingRing_C");

}

