#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ambient_GunfireListener

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Ambient_GunfireListener.BP_Ambient_GunfireListener_C
// 0x0040 (0x0260 - 0x0220)
class ABP_Ambient_GunfireListener_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USphereComponent*                       OverlapSphere;                                     // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Radius;                                            // 0x0230(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PercentChance;                                     // 0x0234(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LastAudioPlayedTime;                               // 0x0238(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CooldownTimeThreshold;                             // 0x023C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              RandomDelayRange;                                  // 0x0240(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             SoundToPlay;                                       // 0x0248(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          LocalPawnInside;                                   // 0x0250(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_251[0x7];                                      // 0x0251(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPawn*                              LocalPawn;                                         // 0x0258(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void BndEvt__OverlapSphere_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);
	void BndEvt__OverlapSphere_K2Node_ComponentBoundEvent_5_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
	void On_Pawn_Weapon_Equipped(class AFortWeapon* NewWeapon, class AFortWeapon* PrevWeapon);
	void On_Weapon_Fire(class AFortWeapon* Weapon);
	void PawnOverlapBegin(class AActor* Pawn);
	void PawnOverlapEnd(class AActor* Pawn);
	void ExecuteUbergraph_BP_Ambient_GunfireListener(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Ambient_GunfireListener_C">();
	}
	static class ABP_Ambient_GunfireListener_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Ambient_GunfireListener_C>();
	}
};
static_assert(alignof(ABP_Ambient_GunfireListener_C) == 0x000008, "Wrong alignment on ABP_Ambient_GunfireListener_C");
static_assert(sizeof(ABP_Ambient_GunfireListener_C) == 0x000260, "Wrong size on ABP_Ambient_GunfireListener_C");
static_assert(offsetof(ABP_Ambient_GunfireListener_C, UberGraphFrame) == 0x000220, "Member 'ABP_Ambient_GunfireListener_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_Ambient_GunfireListener_C, OverlapSphere) == 0x000228, "Member 'ABP_Ambient_GunfireListener_C::OverlapSphere' has a wrong offset!");
static_assert(offsetof(ABP_Ambient_GunfireListener_C, Radius) == 0x000230, "Member 'ABP_Ambient_GunfireListener_C::Radius' has a wrong offset!");
static_assert(offsetof(ABP_Ambient_GunfireListener_C, PercentChance) == 0x000234, "Member 'ABP_Ambient_GunfireListener_C::PercentChance' has a wrong offset!");
static_assert(offsetof(ABP_Ambient_GunfireListener_C, LastAudioPlayedTime) == 0x000238, "Member 'ABP_Ambient_GunfireListener_C::LastAudioPlayedTime' has a wrong offset!");
static_assert(offsetof(ABP_Ambient_GunfireListener_C, CooldownTimeThreshold) == 0x00023C, "Member 'ABP_Ambient_GunfireListener_C::CooldownTimeThreshold' has a wrong offset!");
static_assert(offsetof(ABP_Ambient_GunfireListener_C, RandomDelayRange) == 0x000240, "Member 'ABP_Ambient_GunfireListener_C::RandomDelayRange' has a wrong offset!");
static_assert(offsetof(ABP_Ambient_GunfireListener_C, SoundToPlay) == 0x000248, "Member 'ABP_Ambient_GunfireListener_C::SoundToPlay' has a wrong offset!");
static_assert(offsetof(ABP_Ambient_GunfireListener_C, LocalPawnInside) == 0x000250, "Member 'ABP_Ambient_GunfireListener_C::LocalPawnInside' has a wrong offset!");
static_assert(offsetof(ABP_Ambient_GunfireListener_C, LocalPawn) == 0x000258, "Member 'ABP_Ambient_GunfireListener_C::LocalPawn' has a wrong offset!");

}

