#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AthenaQuestPanelControlsWidget

#include "Basic.hpp"

#include "BP_AthenaQuestPanelControlsWidget_classes.hpp"
#include "BP_AthenaQuestPanelControlsWidget_parameters.hpp"


namespace SDK
{

// Function BP_AthenaQuestPanelControlsWidget.BP_AthenaQuestPanelControlsWidget_C.ExecuteUbergraph_BP_AthenaQuestPanelControlsWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AthenaQuestPanelControlsWidget_C::ExecuteUbergraph_BP_AthenaQuestPanelControlsWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_BP_AthenaQuestPanelControlsWidget");

	Params::BP_AthenaQuestPanelControlsWidget_C_ExecuteUbergraph_BP_AthenaQuestPanelControlsWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AthenaQuestPanelControlsWidget.BP_AthenaQuestPanelControlsWidget_C.BP_OnSortTypeTextChanged
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             TypeText                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UBP_AthenaQuestPanelControlsWidget_C::BP_OnSortTypeTextChanged(const class FText& TypeText)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BP_OnSortTypeTextChanged");

	Params::BP_AthenaQuestPanelControlsWidget_C_BP_OnSortTypeTextChanged Parms{};

	Parms.TypeText = std::move(TypeText);

	UObject::ProcessEvent(Func, &Parms);
}

}

