#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CalendarDynamicPOIMultiple

#include "Basic.hpp"

#include "BP_CalendarDynamicPOIMultiple_classes.hpp"
#include "BP_CalendarDynamicPOIMultiple_parameters.hpp"


namespace SDK
{

// Function BP_CalendarDynamicPOIMultiple.BP_CalendarDynamicPOIMultiple_C.ExecuteUbergraph_BP_CalendarDynamicPOIMultiple
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CalendarDynamicPOIMultiple_C::ExecuteUbergraph_BP_CalendarDynamicPOIMultiple(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_BP_CalendarDynamicPOIMultiple");

	Params::BP_CalendarDynamicPOIMultiple_C_ExecuteUbergraph_BP_CalendarDynamicPOIMultiple Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CalendarDynamicPOIMultiple.BP_CalendarDynamicPOIMultiple_C.EnableNewFoundations
// (BlueprintCallable, BlueprintEvent)

void ABP_CalendarDynamicPOIMultiple_C::EnableNewFoundations()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EnableNewFoundations");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CalendarDynamicPOIMultiple.BP_CalendarDynamicPOIMultiple_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CalendarDynamicPOIMultiple_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CalendarDynamicPOIMultiple.BP_CalendarDynamicPOIMultiple_C.OnReady_852DBB444CF752ECDF6369A616C2467F
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortGameStateAthena*             GameState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFortPlaylist*                    Playlist                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTagContainer            PlaylistContextTags                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_CalendarDynamicPOIMultiple_C::OnReady_852DBB444CF752ECDF6369A616C2467F(class AFortGameStateAthena* GameState, const class UFortPlaylist* Playlist, const struct FGameplayTagContainer& PlaylistContextTags)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnReady_852DBB444CF752ECDF6369A616C2467F");

	Params::BP_CalendarDynamicPOIMultiple_C_OnReady_852DBB444CF752ECDF6369A616C2467F Parms{};

	Parms.GameState = GameState;
	Parms.Playlist = Playlist;
	Parms.PlaylistContextTags = std::move(PlaylistContextTags);

	UObject::ProcessEvent(Func, &Parms);
}

}

