#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CalendarProvider_MultiSpot

#include "Basic.hpp"

#include "BP_CalendarProvider_MultiSpot_classes.hpp"
#include "BP_CalendarProvider_MultiSpot_parameters.hpp"


namespace SDK
{

// Function BP_CalendarProvider_MultiSpot.BP_CalendarProvider_MultiSpot_C.ExecuteUbergraph_BP_CalendarProvider_MultiSpot
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CalendarProvider_MultiSpot_C::ExecuteUbergraph_BP_CalendarProvider_MultiSpot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_BP_CalendarProvider_MultiSpot");

	Params::BP_CalendarProvider_MultiSpot_C_ExecuteUbergraph_BP_CalendarProvider_MultiSpot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CalendarProvider_MultiSpot.BP_CalendarProvider_MultiSpot_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CalendarProvider_MultiSpot_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CalendarProvider_MultiSpot.BP_CalendarProvider_MultiSpot_C.OnReady_C7DEAF5E4A2B5B7CF34AFABBEAA1DB35
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortGameStateAthena*             GameState                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UFortPlaylist*                    Playlist                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTagContainer            PlaylistContextTags                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_CalendarProvider_MultiSpot_C::OnReady_C7DEAF5E4A2B5B7CF34AFABBEAA1DB35(class AFortGameStateAthena* GameState, const class UFortPlaylist* Playlist, const struct FGameplayTagContainer& PlaylistContextTags)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnReady_C7DEAF5E4A2B5B7CF34AFABBEAA1DB35");

	Params::BP_CalendarProvider_MultiSpot_C_OnReady_C7DEAF5E4A2B5B7CF34AFABBEAA1DB35 Parms{};

	Parms.GameState = GameState;
	Parms.Playlist = Playlist;
	Parms.PlaylistContextTags = std::move(PlaylistContextTags);

	UObject::ProcessEvent(Func, &Parms);
}

}

