#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Decal_Wasabi_Marking

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Decal_Wasabi_Marking.BP_Decal_Wasabi_Marking_C
// 0x0020 (0x0248 - 0x0228)
class ABP_Decal_Wasabi_Marking_C final : public ADecalActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UMaterialInterface*                     StoneDecal;                                        // 0x0230(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     WoodDecal;                                         // 0x0238(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     MetalDecal;                                        // 0x0240(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Decal_Wasabi_Marking(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Decal_Wasabi_Marking_C">();
	}
	static class ABP_Decal_Wasabi_Marking_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Decal_Wasabi_Marking_C>();
	}
};
static_assert(alignof(ABP_Decal_Wasabi_Marking_C) == 0x000008, "Wrong alignment on ABP_Decal_Wasabi_Marking_C");
static_assert(sizeof(ABP_Decal_Wasabi_Marking_C) == 0x000248, "Wrong size on ABP_Decal_Wasabi_Marking_C");
static_assert(offsetof(ABP_Decal_Wasabi_Marking_C, UberGraphFrame) == 0x000228, "Member 'ABP_Decal_Wasabi_Marking_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_Decal_Wasabi_Marking_C, StoneDecal) == 0x000230, "Member 'ABP_Decal_Wasabi_Marking_C::StoneDecal' has a wrong offset!");
static_assert(offsetof(ABP_Decal_Wasabi_Marking_C, WoodDecal) == 0x000238, "Member 'ABP_Decal_Wasabi_Marking_C::WoodDecal' has a wrong offset!");
static_assert(offsetof(ABP_Decal_Wasabi_Marking_C, MetalDecal) == 0x000240, "Member 'ABP_Decal_Wasabi_Marking_C::MetalDecal' has a wrong offset!");

}

