#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Doggus_FloatingPlatform_Lights

#include "Basic.hpp"

#include "BP_Doggus_FloatingPlatform_Lights_classes.hpp"
#include "BP_Doggus_FloatingPlatform_Lights_parameters.hpp"


namespace SDK
{

// Function BP_Doggus_FloatingPlatform_Lights.BP_Doggus_FloatingPlatform_Lights_C.ExecuteUbergraph_BP_Doggus_FloatingPlatform_Lights
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Doggus_FloatingPlatform_Lights_C::ExecuteUbergraph_BP_Doggus_FloatingPlatform_Lights(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_BP_Doggus_FloatingPlatform_Lights");

	Params::BP_Doggus_FloatingPlatform_Lights_C_ExecuteUbergraph_BP_Doggus_FloatingPlatform_Lights Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Doggus_FloatingPlatform_Lights.BP_Doggus_FloatingPlatform_Lights_C.DeactivateLights
// (BlueprintCallable, BlueprintEvent)

void ABP_Doggus_FloatingPlatform_Lights_C::DeactivateLights()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("DeactivateLights");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Doggus_FloatingPlatform_Lights.BP_Doggus_FloatingPlatform_Lights_C.ActivateLights
// (BlueprintCallable, BlueprintEvent)

void ABP_Doggus_FloatingPlatform_Lights_C::ActivateLights()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ActivateLights");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Doggus_FloatingPlatform_Lights.BP_Doggus_FloatingPlatform_Lights_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Doggus_FloatingPlatform_Lights_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

