#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FogVolume

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_FogVolume.BP_FogVolume_C.ExecuteUbergraph_BP_FogVolume
// 0x0004 (0x0004 - 0x0000)
struct BP_FogVolume_C_ExecuteUbergraph_BP_FogVolume final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_FogVolume_C_ExecuteUbergraph_BP_FogVolume) == 0x000004, "Wrong alignment on BP_FogVolume_C_ExecuteUbergraph_BP_FogVolume");
static_assert(sizeof(BP_FogVolume_C_ExecuteUbergraph_BP_FogVolume) == 0x000004, "Wrong size on BP_FogVolume_C_ExecuteUbergraph_BP_FogVolume");
static_assert(offsetof(BP_FogVolume_C_ExecuteUbergraph_BP_FogVolume, EntryPoint) == 0x000000, "Member 'BP_FogVolume_C_ExecuteUbergraph_BP_FogVolume::EntryPoint' has a wrong offset!");

// Function BP_FogVolume.BP_FogVolume_C.SetScalarOnFogMaterial
// 0x000C (0x000C - 0x0000)
struct BP_FogVolume_C_SetScalarOnFogMaterial final
{
public:
	float                                         Value;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Name_0;                                            // 0x0004(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_FogVolume_C_SetScalarOnFogMaterial) == 0x000004, "Wrong alignment on BP_FogVolume_C_SetScalarOnFogMaterial");
static_assert(sizeof(BP_FogVolume_C_SetScalarOnFogMaterial) == 0x00000C, "Wrong size on BP_FogVolume_C_SetScalarOnFogMaterial");
static_assert(offsetof(BP_FogVolume_C_SetScalarOnFogMaterial, Value) == 0x000000, "Member 'BP_FogVolume_C_SetScalarOnFogMaterial::Value' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_SetScalarOnFogMaterial, Name_0) == 0x000004, "Member 'BP_FogVolume_C_SetScalarOnFogMaterial::Name_0' has a wrong offset!");

// Function BP_FogVolume.BP_FogVolume_C.UpdateMaterial
// 0x00B8 (0x00B8 - 0x0000)
struct BP_FogVolume_C_UpdateMaterial final
{
public:
	struct FLinearColor                           CallFunc_Conv_VectorToLinearColor_ReturnValue;     // 0x0000(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_Conv_VectorToLinearColor_ReturnValue_1;   // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_Conv_VectorToLinearColor_ReturnValue_2;   // 0x0020(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_Conv_VectorToLinearColor_ReturnValue_3;   // 0x0030(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_Conv_VectorToLinearColor_ReturnValue_4;   // 0x0044(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_Conv_VectorToLinearColor_ReturnValue_5;   // 0x0054(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetComponentBounds_Origin;                // 0x0064(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetComponentBounds_BoxExtent;             // 0x0070(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetComponentBounds_SphereRadius;          // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0080(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x008C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_Conv_VectorToLinearColor_ReturnValue_6;   // 0x0098(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_Conv_VectorToLinearColor_ReturnValue_7;   // 0x00A8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_FogVolume_C_UpdateMaterial) == 0x000004, "Wrong alignment on BP_FogVolume_C_UpdateMaterial");
static_assert(sizeof(BP_FogVolume_C_UpdateMaterial) == 0x0000B8, "Wrong size on BP_FogVolume_C_UpdateMaterial");
static_assert(offsetof(BP_FogVolume_C_UpdateMaterial, CallFunc_Conv_VectorToLinearColor_ReturnValue) == 0x000000, "Member 'BP_FogVolume_C_UpdateMaterial::CallFunc_Conv_VectorToLinearColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_UpdateMaterial, CallFunc_Conv_VectorToLinearColor_ReturnValue_1) == 0x000010, "Member 'BP_FogVolume_C_UpdateMaterial::CallFunc_Conv_VectorToLinearColor_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_UpdateMaterial, CallFunc_Conv_VectorToLinearColor_ReturnValue_2) == 0x000020, "Member 'BP_FogVolume_C_UpdateMaterial::CallFunc_Conv_VectorToLinearColor_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_UpdateMaterial, CallFunc_Conv_VectorToLinearColor_ReturnValue_3) == 0x000030, "Member 'BP_FogVolume_C_UpdateMaterial::CallFunc_Conv_VectorToLinearColor_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_UpdateMaterial, K2Node_SwitchInteger_CmpSuccess) == 0x000040, "Member 'BP_FogVolume_C_UpdateMaterial::K2Node_SwitchInteger_CmpSuccess' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_UpdateMaterial, CallFunc_Conv_VectorToLinearColor_ReturnValue_4) == 0x000044, "Member 'BP_FogVolume_C_UpdateMaterial::CallFunc_Conv_VectorToLinearColor_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_UpdateMaterial, CallFunc_Conv_VectorToLinearColor_ReturnValue_5) == 0x000054, "Member 'BP_FogVolume_C_UpdateMaterial::CallFunc_Conv_VectorToLinearColor_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_UpdateMaterial, CallFunc_GetComponentBounds_Origin) == 0x000064, "Member 'BP_FogVolume_C_UpdateMaterial::CallFunc_GetComponentBounds_Origin' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_UpdateMaterial, CallFunc_GetComponentBounds_BoxExtent) == 0x000070, "Member 'BP_FogVolume_C_UpdateMaterial::CallFunc_GetComponentBounds_BoxExtent' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_UpdateMaterial, CallFunc_GetComponentBounds_SphereRadius) == 0x00007C, "Member 'BP_FogVolume_C_UpdateMaterial::CallFunc_GetComponentBounds_SphereRadius' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_UpdateMaterial, CallFunc_Add_VectorVector_ReturnValue) == 0x000080, "Member 'BP_FogVolume_C_UpdateMaterial::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_UpdateMaterial, CallFunc_Subtract_VectorVector_ReturnValue) == 0x00008C, "Member 'BP_FogVolume_C_UpdateMaterial::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_UpdateMaterial, CallFunc_Conv_VectorToLinearColor_ReturnValue_6) == 0x000098, "Member 'BP_FogVolume_C_UpdateMaterial::CallFunc_Conv_VectorToLinearColor_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_UpdateMaterial, CallFunc_Conv_VectorToLinearColor_ReturnValue_7) == 0x0000A8, "Member 'BP_FogVolume_C_UpdateMaterial::CallFunc_Conv_VectorToLinearColor_ReturnValue_7' has a wrong offset!");

// Function BP_FogVolume.BP_FogVolume_C.SetVectorOnFogMaterial
// 0x0018 (0x0018 - 0x0000)
struct BP_FogVolume_C_SetVectorOnFogMaterial final
{
public:
	struct FLinearColor                           Value;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Name_0;                                            // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_FogVolume_C_SetVectorOnFogMaterial) == 0x000004, "Wrong alignment on BP_FogVolume_C_SetVectorOnFogMaterial");
static_assert(sizeof(BP_FogVolume_C_SetVectorOnFogMaterial) == 0x000018, "Wrong size on BP_FogVolume_C_SetVectorOnFogMaterial");
static_assert(offsetof(BP_FogVolume_C_SetVectorOnFogMaterial, Value) == 0x000000, "Member 'BP_FogVolume_C_SetVectorOnFogMaterial::Value' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_SetVectorOnFogMaterial, Name_0) == 0x000010, "Member 'BP_FogVolume_C_SetVectorOnFogMaterial::Name_0' has a wrong offset!");

// Function BP_FogVolume.BP_FogVolume_C.updateParticle
// 0x00A8 (0x00A8 - 0x0000)
struct BP_FogVolume_C_updateParticle final
{
public:
	class UMaterialInterface*                     Temp_object_Variable;                              // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     Temp_object_Variable_1;                            // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     Temp_object_Variable_2;                            // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0028(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_X;                            // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_59[0x3];                                       // 0x0059(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue_1;             // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0068(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UMaterialInterface*                     K2Node_Select_Default;                             // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0080(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UMaterialInterface*                     K2Node_Select_Default_1;                           // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue;            // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_FogVolume_C_updateParticle) == 0x000008, "Wrong alignment on BP_FogVolume_C_updateParticle");
static_assert(sizeof(BP_FogVolume_C_updateParticle) == 0x0000A8, "Wrong size on BP_FogVolume_C_updateParticle");
static_assert(offsetof(BP_FogVolume_C_updateParticle, Temp_object_Variable) == 0x000000, "Member 'BP_FogVolume_C_updateParticle::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, Temp_bool_Variable) == 0x000008, "Member 'BP_FogVolume_C_updateParticle::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, Temp_object_Variable_1) == 0x000010, "Member 'BP_FogVolume_C_updateParticle::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, Temp_object_Variable_2) == 0x000018, "Member 'BP_FogVolume_C_updateParticle::Temp_object_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, Temp_int_Variable) == 0x000020, "Member 'BP_FogVolume_C_updateParticle::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, CallFunc_IsValid_ReturnValue) == 0x000024, "Member 'BP_FogVolume_C_updateParticle::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000028, "Member 'BP_FogVolume_C_updateParticle::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, CallFunc_GetDisplayName_ReturnValue) == 0x000038, "Member 'BP_FogVolume_C_updateParticle::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, CallFunc_BreakVector_X) == 0x000048, "Member 'BP_FogVolume_C_updateParticle::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, CallFunc_BreakVector_Y) == 0x00004C, "Member 'BP_FogVolume_C_updateParticle::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, CallFunc_BreakVector_Z) == 0x000050, "Member 'BP_FogVolume_C_updateParticle::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, CallFunc_Add_FloatFloat_ReturnValue) == 0x000054, "Member 'BP_FogVolume_C_updateParticle::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, CallFunc_IsValid_ReturnValue_1) == 0x000058, "Member 'BP_FogVolume_C_updateParticle::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, CallFunc_Add_FloatFloat_ReturnValue_1) == 0x00005C, "Member 'BP_FogVolume_C_updateParticle::CallFunc_Add_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000060, "Member 'BP_FogVolume_C_updateParticle::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, CallFunc_FTrunc_ReturnValue) == 0x000064, "Member 'BP_FogVolume_C_updateParticle::CallFunc_FTrunc_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, CallFunc_Conv_IntToString_ReturnValue) == 0x000068, "Member 'BP_FogVolume_C_updateParticle::CallFunc_Conv_IntToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, K2Node_Select_Default) == 0x000078, "Member 'BP_FogVolume_C_updateParticle::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, CallFunc_Concat_StrStr_ReturnValue) == 0x000080, "Member 'BP_FogVolume_C_updateParticle::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, K2Node_Select_Default_1) == 0x000090, "Member 'BP_FogVolume_C_updateParticle::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, CallFunc_Conv_StringToName_ReturnValue) == 0x000098, "Member 'BP_FogVolume_C_updateParticle::CallFunc_Conv_StringToName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_FogVolume_C_updateParticle, CallFunc_CreateDynamicMaterialInstance_ReturnValue) == 0x0000A0, "Member 'BP_FogVolume_C_updateParticle::CallFunc_CreateDynamicMaterialInstance_ReturnValue' has a wrong offset!");

}

