#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Pickle_Portal_Parent

#include "Basic.hpp"

#include "BP_Pickle_Portal_Parent_classes.hpp"
#include "BP_Pickle_Portal_Parent_parameters.hpp"


namespace SDK
{

// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.OnRep_Progress
// (BlueprintCallable, BlueprintEvent)

void ABP_Pickle_Portal_Parent_C::OnRep_Progress()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnRep_Progress");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.UpdateProgress
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Pickle_Portal_Parent_C::UpdateProgress()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateProgress");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.SmoothTangents
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          Location_A                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Tangent_A                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Location_B                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Tangent_B                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Tangent_0                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Tangent_1                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pickle_Portal_Parent_C::SmoothTangents(const struct FVector& Location_A, const struct FVector& Tangent_A, const struct FVector& Location_B, const struct FVector& Tangent_B, struct FVector* Tangent_0, struct FVector* Tangent_1)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SmoothTangents");

	Params::BP_Pickle_Portal_Parent_C_SmoothTangents Parms{};

	Parms.Location_A = std::move(Location_A);
	Parms.Tangent_A = std::move(Tangent_A);
	Parms.Location_B = std::move(Location_B);
	Parms.Tangent_B = std::move(Tangent_B);

	UObject::ProcessEvent(Func, &Parms);

	if (Tangent_0 != nullptr)
		*Tangent_0 = std::move(Parms.Tangent_0);

	if (Tangent_1 != nullptr)
		*Tangent_1 = std::move(Parms.Tangent_1);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Pickle_Portal_Parent_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.OnLoaded_16F3D83F408D5A91E4B0D7BF83CBC7FD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pickle_Portal_Parent_C::OnLoaded_16F3D83F408D5A91E4B0D7BF83CBC7FD(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnLoaded_16F3D83F408D5A91E4B0D7BF83CBC7FD");

	Params::BP_Pickle_Portal_Parent_C_OnLoaded_16F3D83F408D5A91E4B0D7BF83CBC7FD Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.OnEventEnded_9F10F7CE4100D93DAE44FEB0BF074B83
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           EventName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// struct FTimespan                        TimeUntilEnd                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FTimespan                        TimeSinceBegin                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   TimespanRatio                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pickle_Portal_Parent_C::OnEventEnded_9F10F7CE4100D93DAE44FEB0BF074B83(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnEventEnded_9F10F7CE4100D93DAE44FEB0BF074B83");

	Params::BP_Pickle_Portal_Parent_C_OnEventEnded_9F10F7CE4100D93DAE44FEB0BF074B83 Parms{};

	Parms.EventName = std::move(EventName);
	Parms.TimeUntilEnd = std::move(TimeUntilEnd);
	Parms.TimeSinceBegin = std::move(TimeSinceBegin);
	Parms.TimespanRatio = TimespanRatio;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.OnEventUpdated_9F10F7CE4100D93DAE44FEB0BF074B83
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           EventName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// struct FTimespan                        TimeUntilEnd                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FTimespan                        TimeSinceBegin                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   TimespanRatio                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pickle_Portal_Parent_C::OnEventUpdated_9F10F7CE4100D93DAE44FEB0BF074B83(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnEventUpdated_9F10F7CE4100D93DAE44FEB0BF074B83");

	Params::BP_Pickle_Portal_Parent_C_OnEventUpdated_9F10F7CE4100D93DAE44FEB0BF074B83 Parms{};

	Parms.EventName = std::move(EventName);
	Parms.TimeUntilEnd = std::move(TimeUntilEnd);
	Parms.TimeSinceBegin = std::move(TimeSinceBegin);
	Parms.TimespanRatio = TimespanRatio;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.OnEventActive_9F10F7CE4100D93DAE44FEB0BF074B83
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           EventName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// struct FTimespan                        TimeUntilEnd                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FTimespan                        TimeSinceBegin                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   TimespanRatio                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pickle_Portal_Parent_C::OnEventActive_9F10F7CE4100D93DAE44FEB0BF074B83(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnEventActive_9F10F7CE4100D93DAE44FEB0BF074B83");

	Params::BP_Pickle_Portal_Parent_C_OnEventActive_9F10F7CE4100D93DAE44FEB0BF074B83 Parms{};

	Parms.EventName = std::move(EventName);
	Parms.TimeUntilEnd = std::move(TimeUntilEnd);
	Parms.TimeSinceBegin = std::move(TimeSinceBegin);
	Parms.TimespanRatio = TimespanRatio;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.OnLoaded_055E369F4F34EEF69E0D2885290A0116
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pickle_Portal_Parent_C::OnLoaded_055E369F4F34EEF69E0D2885290A0116(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnLoaded_055E369F4F34EEF69E0D2885290A0116");

	Params::BP_Pickle_Portal_Parent_C_OnLoaded_055E369F4F34EEF69E0D2885290A0116 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.OnEventEnded_13D2BC18441919FF8D609E9E466C27CD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           EventName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// struct FTimespan                        TimeUntilEnd                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FTimespan                        TimeSinceBegin                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   TimespanRatio                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pickle_Portal_Parent_C::OnEventEnded_13D2BC18441919FF8D609E9E466C27CD(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnEventEnded_13D2BC18441919FF8D609E9E466C27CD");

	Params::BP_Pickle_Portal_Parent_C_OnEventEnded_13D2BC18441919FF8D609E9E466C27CD Parms{};

	Parms.EventName = std::move(EventName);
	Parms.TimeUntilEnd = std::move(TimeUntilEnd);
	Parms.TimeSinceBegin = std::move(TimeSinceBegin);
	Parms.TimespanRatio = TimespanRatio;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.OnEventUpdated_13D2BC18441919FF8D609E9E466C27CD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           EventName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// struct FTimespan                        TimeUntilEnd                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FTimespan                        TimeSinceBegin                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   TimespanRatio                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pickle_Portal_Parent_C::OnEventUpdated_13D2BC18441919FF8D609E9E466C27CD(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnEventUpdated_13D2BC18441919FF8D609E9E466C27CD");

	Params::BP_Pickle_Portal_Parent_C_OnEventUpdated_13D2BC18441919FF8D609E9E466C27CD Parms{};

	Parms.EventName = std::move(EventName);
	Parms.TimeUntilEnd = std::move(TimeUntilEnd);
	Parms.TimeSinceBegin = std::move(TimeSinceBegin);
	Parms.TimespanRatio = TimespanRatio;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.OnEventActive_13D2BC18441919FF8D609E9E466C27CD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           EventName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// struct FTimespan                        TimeUntilEnd                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FTimespan                        TimeSinceBegin                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   TimespanRatio                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pickle_Portal_Parent_C::OnEventActive_13D2BC18441919FF8D609E9E466C27CD(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnEventActive_13D2BC18441919FF8D609E9E466C27CD");

	Params::BP_Pickle_Portal_Parent_C_OnEventActive_13D2BC18441919FF8D609E9E466C27CD Parms{};

	Parms.EventName = std::move(EventName);
	Parms.TimeUntilEnd = std::move(TimeUntilEnd);
	Parms.TimeSinceBegin = std::move(TimeSinceBegin);
	Parms.TimespanRatio = TimespanRatio;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.SpawnPortal
// (BlueprintCallable, BlueprintEvent)

void ABP_Pickle_Portal_Parent_C::SpawnPortal()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SpawnPortal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.UpdateOpenAmount
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   OpenAmount                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pickle_Portal_Parent_C::UpdateOpenAmount(float OpenAmount)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateOpenAmount");

	Params::BP_Pickle_Portal_Parent_C_UpdateOpenAmount Parms{};

	Parms.OpenAmount = OpenAmount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.ReceiveParticleData
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FBasicParticleData>       Data                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// class UNiagaraSystem*                   NiagaraSystem                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pickle_Portal_Parent_C::ReceiveParticleData(const TArray<struct FBasicParticleData>& Data, class UNiagaraSystem* NiagaraSystem)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveParticleData");

	Params::BP_Pickle_Portal_Parent_C_ReceiveParticleData Parms{};

	Parms.Data = std::move(Data);
	Parms.NiagaraSystem = NiagaraSystem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Pickle_Portal_Parent_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Pickle_Portal_Parent.BP_Pickle_Portal_Parent_C.ExecuteUbergraph_BP_Pickle_Portal_Parent
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pickle_Portal_Parent_C::ExecuteUbergraph_BP_Pickle_Portal_Parent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_BP_Pickle_Portal_Parent");

	Params::BP_Pickle_Portal_Parent_C_ExecuteUbergraph_BP_Pickle_Portal_Parent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

