#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ShootingTarget

#include "Basic.hpp"

#include "BP_ShootingTarget_classes.hpp"
#include "BP_ShootingTarget_parameters.hpp"


namespace SDK
{

// Function BP_ShootingTarget.BP_ShootingTarget_C.ExecuteUbergraph_BP_ShootingTarget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ShootingTarget_C::ExecuteUbergraph_BP_ShootingTarget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_BP_ShootingTarget");

	Params::BP_ShootingTarget_C_ExecuteUbergraph_BP_ShootingTarget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.Award Quest Progress
// (BlueprintCallable, BlueprintEvent)

void ABP_ShootingTarget_C::Award_Quest_Progress()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Award Quest Progress");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.PlayerSteppedOff
// (BlueprintCallable, BlueprintEvent)

void ABP_ShootingTarget_C::PlayerSteppedOff()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PlayerSteppedOff");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.ClearDeactivate
// (BlueprintCallable, BlueprintEvent)

void ABP_ShootingTarget_C::ClearDeactivate()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ClearDeactivate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.CloseTarget
// (BlueprintCallable, BlueprintEvent)

void ABP_ShootingTarget_C::CloseTarget()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("CloseTarget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.OpenTarget
// (BlueprintCallable, BlueprintEvent)

void ABP_ShootingTarget_C::OpenTarget()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OpenTarget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.SampleDamage
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           DamagedActor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AController*                      InstigatedBy                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          HitLocation                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              FHitComponent                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             BoneName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Momentum                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ShootingTarget_C::SampleDamage(class AActor* DamagedActor, float Damage, class AController* InstigatedBy, class AActor* DamageCauser, const struct FVector& HitLocation, class UPrimitiveComponent* FHitComponent, class FName BoneName, const struct FVector& Momentum)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SampleDamage");

	Params::BP_ShootingTarget_C_SampleDamage Parms{};

	Parms.DamagedActor = DamagedActor;
	Parms.Damage = Damage;
	Parms.InstigatedBy = InstigatedBy;
	Parms.DamageCauser = DamageCauser;
	Parms.HitLocation = std::move(HitLocation);
	Parms.FHitComponent = FHitComponent;
	Parms.BoneName = BoneName;
	Parms.Momentum = std::move(Momentum);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.DeactivateBoard
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ShootingTarget_C::DeactivateBoard()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("DeactivateBoard");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.ActivateBoard
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   BoardID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CurrentRound_0                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ShootingTarget_C::ActivateBoard(int32 BoardID, int32 CurrentRound_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ActivateBoard");

	Params::BP_ShootingTarget_C_ActivateBoard Parms{};

	Parms.BoardID = BoardID;
	Parms.CurrentRound_0 = CurrentRound_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.ResetAll
// (BlueprintCallable, BlueprintEvent)

void ABP_ShootingTarget_C::ResetAll()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ResetAll");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_ShootingTarget_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.TargetEnd
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Score                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   BoardID                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ShootingTarget_C::TargetEnd(int32 Score, int32 BoardID)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TargetEnd");

	Params::BP_ShootingTarget_C_TargetEnd Parms{};

	Parms.Score = Score;
	Parms.BoardID = BoardID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.BeginGame
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ShootingTarget_C::BeginGame()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BeginGame");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.CloseBoard__UpdateFunc
// (BlueprintEvent)

void ABP_ShootingTarget_C::CloseBoard__UpdateFunc()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("CloseBoard__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.CloseBoard__FinishedFunc
// (BlueprintEvent)

void ABP_ShootingTarget_C::CloseBoard__FinishedFunc()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("CloseBoard__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.FlipTimeline__UpdateFunc
// (BlueprintEvent)

void ABP_ShootingTarget_C::FlipTimeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("FlipTimeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.FlipTimeline__FinishedFunc
// (BlueprintEvent)

void ABP_ShootingTarget_C::FlipTimeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("FlipTimeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.OnRep_bAlive
// (BlueprintCallable, BlueprintEvent)

void ABP_ShootingTarget_C::OnRep_bAlive()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnRep_bAlive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.OnRep_BoardRotation
// (BlueprintCallable, BlueprintEvent)

void ABP_ShootingTarget_C::OnRep_BoardRotation()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnRep_BoardRotation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.OnRep_bScored
// (BlueprintCallable, BlueprintEvent)

void ABP_ShootingTarget_C::OnRep_bScored()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnRep_bScored");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.OnRep_bReady
// (HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_ShootingTarget_C::OnRep_bReady()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnRep_bReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ShootingTarget.BP_ShootingTarget_C.OnRep_GamePad
// (BlueprintCallable, BlueprintEvent)

void ABP_ShootingTarget_C::OnRep_GamePad()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnRep_GamePad");

	UObject::ProcessEvent(Func, nullptr);
}

}

