#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TRV_CAS_bed_Prison

#include "Basic.hpp"

#include "Bed_parent_Container_Athena_NoSearch_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TRV_CAS_bed_Prison.BP_TRV_CAS_bed_Prison_C
// 0x0000 (0x0D80 - 0x0D80)
class ABP_TRV_CAS_bed_Prison_C final : public ABed_parent_Container_Athena_NoSearch_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_TRV_CAS_bed_Prison_C">();
	}
	static class ABP_TRV_CAS_bed_Prison_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TRV_CAS_bed_Prison_C>();
	}
};
static_assert(alignof(ABP_TRV_CAS_bed_Prison_C) == 0x000008, "Wrong alignment on ABP_TRV_CAS_bed_Prison_C");
static_assert(sizeof(ABP_TRV_CAS_bed_Prison_C) == 0x000D80, "Wrong size on ABP_TRV_CAS_bed_Prison_C");

}

