#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BrickSimple_Chimney_B_Fireplace

#include "Basic.hpp"

#include "BrickSimple_Chimney_B_Fireplace_classes.hpp"
#include "BrickSimple_Chimney_B_Fireplace_parameters.hpp"


namespace SDK
{

// Function BrickSimple_Chimney_B_Fireplace.BrickSimple_Chimney_B_Fireplace_C.ExecuteUbergraph_BrickSimple_Chimney_B_Fireplace
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABrickSimple_Chimney_B_Fireplace_C::ExecuteUbergraph_BrickSimple_Chimney_B_Fireplace(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_BrickSimple_Chimney_B_Fireplace");

	Params::BrickSimple_Chimney_B_Fireplace_C_ExecuteUbergraph_BrickSimple_Chimney_B_Fireplace Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BrickSimple_Chimney_B_Fireplace.BrickSimple_Chimney_B_Fireplace_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABrickSimple_Chimney_B_Fireplace_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BrickSimple_Chimney_B_Fireplace.BrickSimple_Chimney_B_Fireplace_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABrickSimple_Chimney_B_Fireplace_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

