#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CBGA_Athena_ZeroPoint

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function CBGA_Athena_ZeroPoint.CBGA_Athena_ZeroPoint_C.ExecuteUbergraph_CBGA_Athena_ZeroPoint
// 0x0070 (0x0070 - 0x0000)
struct CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DelayBeforeImpulse;                   // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DelayBeforeCollision;                 // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_Event_ImpulseOrigin;                        // 0x000C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_Event_ImpulseAmount;                        // 0x0018(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_SetCollisionAfterImpulse;             // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakVector_X;                            // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0034(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0040(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Normal_ReturnValue;                       // 0x004C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorVector_ReturnValue;        // 0x0058(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorFloat_ReturnValue;              // 0x0064(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint) == 0x000004, "Wrong alignment on CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint");
static_assert(sizeof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint) == 0x000070, "Wrong size on CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint, EntryPoint) == 0x000000, "Member 'CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint::EntryPoint' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint, K2Node_Event_DelayBeforeImpulse) == 0x000004, "Member 'CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint::K2Node_Event_DelayBeforeImpulse' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint, K2Node_Event_DelayBeforeCollision) == 0x000008, "Member 'CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint::K2Node_Event_DelayBeforeCollision' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint, K2Node_Event_ImpulseOrigin) == 0x00000C, "Member 'CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint::K2Node_Event_ImpulseOrigin' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint, K2Node_Event_ImpulseAmount) == 0x000018, "Member 'CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint::K2Node_Event_ImpulseAmount' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint, K2Node_Event_SetCollisionAfterImpulse) == 0x000024, "Member 'CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint::K2Node_Event_SetCollisionAfterImpulse' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint, CallFunc_BreakVector_X) == 0x000028, "Member 'CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint, CallFunc_BreakVector_Y) == 0x00002C, "Member 'CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint, CallFunc_BreakVector_Z) == 0x000030, "Member 'CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000034, "Member 'CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint, CallFunc_Subtract_VectorVector_ReturnValue) == 0x000040, "Member 'CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint, CallFunc_Normal_ReturnValue) == 0x00004C, "Member 'CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint::CallFunc_Normal_ReturnValue' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint, CallFunc_Multiply_VectorVector_ReturnValue) == 0x000058, "Member 'CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint::CallFunc_Multiply_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint, CallFunc_Add_VectorFloat_ReturnValue) == 0x000064, "Member 'CBGA_Athena_ZeroPoint_C_ExecuteUbergraph_CBGA_Athena_ZeroPoint::CallFunc_Add_VectorFloat_ReturnValue' has a wrong offset!");

// Function CBGA_Athena_ZeroPoint.CBGA_Athena_ZeroPoint_C.Impulse
// 0x0024 (0x0024 - 0x0000)
struct CBGA_Athena_ZeroPoint_C_Impulse final
{
public:
	float                                         DelayBeforeImpulse;                                // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DelayBeforeCollision;                              // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                ImpulseOrigin;                                     // 0x0008(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                ImpulseAmount;                                     // 0x0014(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SetCollisionAfterImpulse;                          // 0x0020(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(CBGA_Athena_ZeroPoint_C_Impulse) == 0x000004, "Wrong alignment on CBGA_Athena_ZeroPoint_C_Impulse");
static_assert(sizeof(CBGA_Athena_ZeroPoint_C_Impulse) == 0x000024, "Wrong size on CBGA_Athena_ZeroPoint_C_Impulse");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_Impulse, DelayBeforeImpulse) == 0x000000, "Member 'CBGA_Athena_ZeroPoint_C_Impulse::DelayBeforeImpulse' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_Impulse, DelayBeforeCollision) == 0x000004, "Member 'CBGA_Athena_ZeroPoint_C_Impulse::DelayBeforeCollision' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_Impulse, ImpulseOrigin) == 0x000008, "Member 'CBGA_Athena_ZeroPoint_C_Impulse::ImpulseOrigin' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_Impulse, ImpulseAmount) == 0x000014, "Member 'CBGA_Athena_ZeroPoint_C_Impulse::ImpulseAmount' has a wrong offset!");
static_assert(offsetof(CBGA_Athena_ZeroPoint_C_Impulse, SetCollisionAfterImpulse) == 0x000020, "Member 'CBGA_Athena_ZeroPoint_C_Impulse::SetCollisionAfterImpulse' has a wrong offset!");

}

