#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Chair_Lobby03

#include "Basic.hpp"

#include "Couch_parent_Container_Athena_NoSearch_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Chair_Lobby03.Chair_Lobby03_C
// 0x0000 (0x0D80 - 0x0D80)
class AChair_Lobby03_C final : public ACouch_parent_Container_Athena_NoSearch_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Chair_Lobby03_C">();
	}
	static class AChair_Lobby03_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AChair_Lobby03_C>();
	}
};
static_assert(alignof(AChair_Lobby03_C) == 0x000008, "Wrong alignment on AChair_Lobby03_C");
static_assert(sizeof(AChair_Lobby03_C) == 0x000D80, "Wrong size on AChair_Lobby03_C");

}

