#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Coliseum_Column_04_Bottom

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Coliseum_Column_04_Bottom.Coliseum_Column_04_Bottom_C
// 0x0000 (0x0AD8 - 0x0AD8)
class AColiseum_Column_04_Bottom_C final : public ABuildingPropCorner
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Coliseum_Column_04_Bottom_C">();
	}
	static class AColiseum_Column_04_Bottom_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AColiseum_Column_04_Bottom_C>();
	}
};
static_assert(alignof(AColiseum_Column_04_Bottom_C) == 0x000008, "Wrong alignment on AColiseum_Column_04_Bottom_C");
static_assert(sizeof(AColiseum_Column_04_Bottom_C) == 0x000AD8, "Wrong size on AColiseum_Column_04_Bottom_C");

}

