#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Coliseum_Wall_02

#include "Basic.hpp"

#include "Parent_BuildingWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Coliseum_Wall_02.Coliseum_Wall_02_C
// 0x0000 (0x0C28 - 0x0C28)
class AColiseum_Wall_02_C final : public AParent_BuildingWall_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Coliseum_Wall_02_C">();
	}
	static class AColiseum_Wall_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AColiseum_Wall_02_C>();
	}
};
static_assert(alignof(AColiseum_Wall_02_C) == 0x000008, "Wrong alignment on AColiseum_Wall_02_C");
static_assert(sizeof(AColiseum_Wall_02_C) == 0x000C28, "Wrong size on AColiseum_Wall_02_C");

}

