#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Core_Event

#include "Basic.hpp"

#include "Core_Event_classes.hpp"
#include "Core_Event_parameters.hpp"


namespace SDK
{

// Function Core_Event.Context_Event_wait.Update
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// int32                                   RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UContext_Event_wait::Update()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Update");

	Params::Context_Event_wait_Update Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Core_Event.Event.$InitCDO
// ()

void UEvent::_InitCDO()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Core_Event.Event.$InitInstance
// ()

void UEvent::_InitInstance()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Core_Event.Event.getWaitCount
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// int32                                   RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

int32 UEvent::getWaitCount()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("getWaitCount");

	Params::Event_getWaitCount Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Core_Event.Event.signal
// (Native, Public, BlueprintCallable)

void UEvent::signal()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("signal");

	UObject::ProcessEvent(Func, nullptr);
}

}

