#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CreativeAffiliatePanel

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass CreativeAffiliatePanel.CreativeAffiliatePanel_C
// 0x0040 (0x04D0 - 0x0490)
class UCreativeAffiliatePanel_C final : public UFortCreativeAffiliatePanel
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0490(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAffiliateKeyModal_C*                   AffiliateKeyModal;                                 // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USoundBase*                             OpenMenuSound;                                     // 0x04A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             CloseMenuSound;                                    // 0x04A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnPanelClose;                                      // 0x04B0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnSuccess;                                         // 0x04C0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ExecuteUbergraph_CreativeAffiliatePanel(int32 EntryPoint);
	void On_Success();
	void InitFromObject(class UObject* InitObject);
	void BP_OnActivated();
	void PopupClosed();
	void ButtonClicked(class UCommonButton* Button);
	void BP_OnDeactivated();
	void Close();
	void SetAffiliateName(const class FText& AffiliateName);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CreativeAffiliatePanel_C">();
	}
	static class UCreativeAffiliatePanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCreativeAffiliatePanel_C>();
	}
};
static_assert(alignof(UCreativeAffiliatePanel_C) == 0x000008, "Wrong alignment on UCreativeAffiliatePanel_C");
static_assert(sizeof(UCreativeAffiliatePanel_C) == 0x0004D0, "Wrong size on UCreativeAffiliatePanel_C");
static_assert(offsetof(UCreativeAffiliatePanel_C, UberGraphFrame) == 0x000490, "Member 'UCreativeAffiliatePanel_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UCreativeAffiliatePanel_C, AffiliateKeyModal) == 0x000498, "Member 'UCreativeAffiliatePanel_C::AffiliateKeyModal' has a wrong offset!");
static_assert(offsetof(UCreativeAffiliatePanel_C, OpenMenuSound) == 0x0004A0, "Member 'UCreativeAffiliatePanel_C::OpenMenuSound' has a wrong offset!");
static_assert(offsetof(UCreativeAffiliatePanel_C, CloseMenuSound) == 0x0004A8, "Member 'UCreativeAffiliatePanel_C::CloseMenuSound' has a wrong offset!");
static_assert(offsetof(UCreativeAffiliatePanel_C, OnPanelClose) == 0x0004B0, "Member 'UCreativeAffiliatePanel_C::OnPanelClose' has a wrong offset!");
static_assert(offsetof(UCreativeAffiliatePanel_C, OnSuccess) == 0x0004C0, "Member 'UCreativeAffiliatePanel_C::OnSuccess' has a wrong offset!");

}

