#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DynamicHUD

#include "Basic.hpp"

#include "DynamicHUD_classes.hpp"
#include "DynamicHUD_parameters.hpp"


namespace SDK
{

// Function DynamicHUD.DynamicHUDManager.AddScene
// (Final, Native, Protected, BlueprintCallable)
// Parameters:
// class UDynamicHUDScene*                 Scene                                                  (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UDynamicHUDManager::AddScene(const class UDynamicHUDScene* Scene)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("AddScene");

	Params::DynamicHUDManager_AddScene Parms{};

	Parms.Scene = Scene;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DynamicHUD.DynamicHUDManager.AddScenes
// (Final, Native, Protected, BlueprintCallable)
// Parameters:
// TArray<class UDynamicHUDScene*>         Scenes                                                 (ConstParm, Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UDynamicHUDManager::AddScenes(const TArray<class UDynamicHUDScene*>& Scenes)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("AddScenes");

	Params::DynamicHUDManager_AddScenes Parms{};

	Parms.Scenes = std::move(Scenes);

	UObject::ProcessEvent(Func, &Parms);
}


// Function DynamicHUD.DynamicHUDManager.GetCurrentWidgetCatalog
// (Final, RequiredAPI, Native, Public, BlueprintCallable)
// Parameters:
// class UDynamicHUDWidgetCatalog*         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UDynamicHUDWidgetCatalog* UDynamicHUDManager::GetCurrentWidgetCatalog()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetCurrentWidgetCatalog");

	Params::DynamicHUDManager_GetCurrentWidgetCatalog Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function DynamicHUD.DynamicHUDManager.RemoveScene
// (Final, Native, Protected, BlueprintCallable)
// Parameters:
// class UDynamicHUDScene*                 Scene                                                  (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UDynamicHUDManager::RemoveScene(const class UDynamicHUDScene* Scene)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("RemoveScene");

	Params::DynamicHUDManager_RemoveScene Parms{};

	Parms.Scene = Scene;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DynamicHUD.DynamicHUDManager.RemoveScenes
// (Final, Native, Protected, BlueprintCallable)
// Parameters:
// TArray<class UDynamicHUDScene*>         Scenes                                                 (ConstParm, Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UDynamicHUDManager::RemoveScenes(const TArray<class UDynamicHUDScene*>& Scenes)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("RemoveScenes");

	Params::DynamicHUDManager_RemoveScenes Parms{};

	Parms.Scenes = std::move(Scenes);

	UObject::ProcessEvent(Func, &Parms);
}


// Function DynamicHUD.DynamicHUDManager.SetCurrentWidgetCatalog
// (Final, RequiredAPI, Native, Public, BlueprintCallable)
// Parameters:
// class UDynamicHUDWidgetCatalog*         InWidgetCatalog                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UDynamicHUDManager::SetCurrentWidgetCatalog(class UDynamicHUDWidgetCatalog* InWidgetCatalog)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetCurrentWidgetCatalog");

	Params::DynamicHUDManager_SetCurrentWidgetCatalog Parms{};

	Parms.InWidgetCatalog = InWidgetCatalog;

	UObject::ProcessEvent(Func, &Parms);
}

}

