#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_HeldObject_Explode

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_HeldObject_Explode.GA_HeldObject_Explode_C
// 0x00C8 (0x0B80 - 0x0AB8)
class UGA_HeldObject_Explode_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AB8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FScalableFloat                         KnockbackStrength;                                 // 0x0AC0(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         VehicleImpulseStrength;                            // 0x0AE8(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         VehicleImpulseStrengthZ;                           // 0x0B10(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	class AActor*                                 CurrentPlayerToLaunch;                             // 0x0B38(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 GE_Explode;                                        // 0x0B40(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Instigator;                                        // 0x0B48(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortAbilitySystemComponent*            InstigatorAbility;                                 // 0x0B50(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         Row_BuildingActorKnockMult;                        // 0x0B58(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_GA_HeldObject_Explode(int32 EntryPoint);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);
	void Targeted_CB46D31E40DE0E96BD9CEBB5B054252D(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void Cancelled_CB46D31E40DE0E96BD9CEBB5B054252D(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	struct FGameplayEffectContextHandle MakeEffectContext();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_HeldObject_Explode_C">();
	}
	static class UGA_HeldObject_Explode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_HeldObject_Explode_C>();
	}
};
static_assert(alignof(UGA_HeldObject_Explode_C) == 0x000008, "Wrong alignment on UGA_HeldObject_Explode_C");
static_assert(sizeof(UGA_HeldObject_Explode_C) == 0x000B80, "Wrong size on UGA_HeldObject_Explode_C");
static_assert(offsetof(UGA_HeldObject_Explode_C, UberGraphFrame) == 0x000AB8, "Member 'UGA_HeldObject_Explode_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UGA_HeldObject_Explode_C, KnockbackStrength) == 0x000AC0, "Member 'UGA_HeldObject_Explode_C::KnockbackStrength' has a wrong offset!");
static_assert(offsetof(UGA_HeldObject_Explode_C, VehicleImpulseStrength) == 0x000AE8, "Member 'UGA_HeldObject_Explode_C::VehicleImpulseStrength' has a wrong offset!");
static_assert(offsetof(UGA_HeldObject_Explode_C, VehicleImpulseStrengthZ) == 0x000B10, "Member 'UGA_HeldObject_Explode_C::VehicleImpulseStrengthZ' has a wrong offset!");
static_assert(offsetof(UGA_HeldObject_Explode_C, CurrentPlayerToLaunch) == 0x000B38, "Member 'UGA_HeldObject_Explode_C::CurrentPlayerToLaunch' has a wrong offset!");
static_assert(offsetof(UGA_HeldObject_Explode_C, GE_Explode) == 0x000B40, "Member 'UGA_HeldObject_Explode_C::GE_Explode' has a wrong offset!");
static_assert(offsetof(UGA_HeldObject_Explode_C, Instigator) == 0x000B48, "Member 'UGA_HeldObject_Explode_C::Instigator' has a wrong offset!");
static_assert(offsetof(UGA_HeldObject_Explode_C, InstigatorAbility) == 0x000B50, "Member 'UGA_HeldObject_Explode_C::InstigatorAbility' has a wrong offset!");
static_assert(offsetof(UGA_HeldObject_Explode_C, Row_BuildingActorKnockMult) == 0x000B58, "Member 'UGA_HeldObject_Explode_C::Row_BuildingActorKnockMult' has a wrong offset!");

}

