#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCL_Cornfield_Movement

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCL_Cornfield_Movement.GCL_Cornfield_Movement_C
// 0x0010 (0x07D0 - 0x07C0)
class AGCL_Cornfield_Movement_C final : public AFortGameplayCueNotify_Loop
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x07C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AFortPlayerPawn*                        TargetPawn;                                        // 0x07C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GCL_Cornfield_Movement(int32 EntryPoint);
	void On_Player_Step();
	void ReceiveBeginPlay();
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	bool OnActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	bool WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCL_Cornfield_Movement_C">();
	}
	static class AGCL_Cornfield_Movement_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCL_Cornfield_Movement_C>();
	}
};
static_assert(alignof(AGCL_Cornfield_Movement_C) == 0x000008, "Wrong alignment on AGCL_Cornfield_Movement_C");
static_assert(sizeof(AGCL_Cornfield_Movement_C) == 0x0007D0, "Wrong size on AGCL_Cornfield_Movement_C");
static_assert(offsetof(AGCL_Cornfield_Movement_C, UberGraphFrame) == 0x0007C0, "Member 'AGCL_Cornfield_Movement_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AGCL_Cornfield_Movement_C, TargetPawn) == 0x0007C8, "Member 'AGCL_Cornfield_Movement_C::TargetPawn' has a wrong offset!");

}

