#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HeroLoadoutActiveAbilitiesDetailLayoutStyle

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum HeroLoadoutActiveAbilitiesDetailLayoutStyle.HeroLoadoutActiveAbilitiesDetailLayoutStyle
// NumValues: 0x0002
enum class EHeroLoadoutActiveAbilitiesDetailLayoutStyle : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
};

}

