#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Lamp02

#include "Basic.hpp"

#include "Parent_BuildingPropActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Lamp02.Lamp02_C
// 0x0008 (0x0C90 - 0x0C88)
class ALamp02_C final : public AParent_BuildingPropActor_C
{
public:
	class UPointLightComponent*                   PointLight;                                        // 0x0C88(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Lamp02_C">();
	}
	static class ALamp02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALamp02_C>();
	}
};
static_assert(alignof(ALamp02_C) == 0x000008, "Wrong alignment on ALamp02_C");
static_assert(sizeof(ALamp02_C) == 0x000C90, "Wrong size on ALamp02_C");
static_assert(offsetof(ALamp02_C, PointLight) == 0x000C88, "Member 'ALamp02_C::PointLight' has a wrong offset!");

}

