#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: M_MED_Galileo_Gondola_AnimBp

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass M_MED_Galileo_Gondola_AnimBp.M_MED_Galileo_Gondola_AnimBp_C
// 0x11B0 (0x1660 - 0x04B0)
class UM_MED_Galileo_Gondola_AnimBp_C final : public UCustomCharacterPartAnimInstance
{
public:
	uint8                                         Pad_4A8[0x8];                                      // 0x04A8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimInstanceSubsystemData             AnimBlueprintClassSubsystem_PropertyAccess;        // 0x04B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4B9[0x7];                                      // 0x04B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x04C0(0x0030)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh;                    // 0x04F0(0x0140)(ContainsInstancedReference)
	struct FAnimNode_RigidBody                    AnimGraphNode_RigidBody;                           // 0x0630(0x0660)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_2;             // 0x0C90(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_2;             // 0x0CB0(0x0020)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;             // 0x0CD0(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_6;                        // 0x0CF0(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_5;                        // 0x0DF8(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_4;                        // 0x0F00(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_3;                        // 0x1008(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_2;                        // 0x1110(0x0108)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone_1;                        // 0x1218(0x0108)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x1320(0x00A0)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;             // 0x13C0(0x0020)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x13E0(0x00C8)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x14A8(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x14D0(0x0028)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x14F8(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x1518(0x0020)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x1538(0x0108)()
	float                                         crouching_alpha;                                   // 0x1640(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         jump_alpha;                                        // 0x1644(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                gravity_override;                                  // 0x1648(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         thigh_up_l;                                        // 0x1654(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         thigh_up_r;                                        // 0x1658(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_M_MED_Galileo_Gondola_AnimBp(int32 EntryPoint);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"M_MED_Galileo_Gondola_AnimBp_C">();
	}
	static class UM_MED_Galileo_Gondola_AnimBp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UM_MED_Galileo_Gondola_AnimBp_C>();
	}
};
static_assert(alignof(UM_MED_Galileo_Gondola_AnimBp_C) == 0x000010, "Wrong alignment on UM_MED_Galileo_Gondola_AnimBp_C");
static_assert(sizeof(UM_MED_Galileo_Gondola_AnimBp_C) == 0x001660, "Wrong size on UM_MED_Galileo_Gondola_AnimBp_C");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, UberGraphFrame) == 0x0004B0, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimBlueprintClassSubsystem_PropertyAccess) == 0x0004B8, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimBlueprintClassSubsystem_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_Root) == 0x0004C0, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_CopyPoseFromMesh) == 0x0004F0, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_CopyPoseFromMesh' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_RigidBody) == 0x000630, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_RigidBody' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_LocalToComponentSpace_2) == 0x000C90, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_LocalToComponentSpace_2' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_ComponentToLocalSpace_2) == 0x000CB0, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_ComponentToLocalSpace_2' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_LocalToComponentSpace_1) == 0x000CD0, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_LocalToComponentSpace_1' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_ModifyBone_6) == 0x000CF0, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_ModifyBone_6' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_ModifyBone_5) == 0x000DF8, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_ModifyBone_5' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_ModifyBone_4) == 0x000F00, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_ModifyBone_4' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_ModifyBone_3) == 0x001008, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_ModifyBone_3' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_ModifyBone_2) == 0x001110, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_ModifyBone_2' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_ModifyBone_1) == 0x001218, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_ModifyBone_1' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_BlendListByBool) == 0x001320, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_BlendListByBool' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_ComponentToLocalSpace_1) == 0x0013C0, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_ComponentToLocalSpace_1' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_SaveCachedPose) == 0x0013E0, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_SaveCachedPose' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_UseCachedPose_1) == 0x0014A8, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_UseCachedPose_1' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_UseCachedPose) == 0x0014D0, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_UseCachedPose' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_LocalToComponentSpace) == 0x0014F8, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_ComponentToLocalSpace) == 0x001518, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, AnimGraphNode_ModifyBone) == 0x001538, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::AnimGraphNode_ModifyBone' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, crouching_alpha) == 0x001640, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::crouching_alpha' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, jump_alpha) == 0x001644, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::jump_alpha' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, gravity_override) == 0x001648, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::gravity_override' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, thigh_up_l) == 0x001654, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::thigh_up_l' has a wrong offset!");
static_assert(offsetof(UM_MED_Galileo_Gondola_AnimBp_C, thigh_up_r) == 0x001658, "Member 'UM_MED_Galileo_Gondola_AnimBp_C::thigh_up_r' has a wrong offset!");

}

