#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Male_Medium_Galileo_Gondola_Head_AnimBp

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Male_Medium_Galileo_Gondola_Head_AnimBp.Male_Medium_Galileo_Gondola_Head_AnimBp_C
// 0x0180 (0x0630 - 0x04B0)
class UMale_Medium_Galileo_Gondola_Head_AnimBp_C final : public UCustomCharacterPartAnimInstance
{
public:
	uint8                                         Pad_4A8[0x8];                                      // 0x04A8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimInstanceSubsystemData             AnimBlueprintClassSubsystem_PropertyAccess;        // 0x04B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4B9[0x7];                                      // 0x04B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x04C0(0x0030)()
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh;                    // 0x04F0(0x0140)(ContainsInstancedReference)

public:
	void ExecuteUbergraph_Male_Medium_Galileo_Gondola_Head_AnimBp(int32 EntryPoint);
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Male_Medium_Galileo_Gondola_Head_AnimBp_C">();
	}
	static class UMale_Medium_Galileo_Gondola_Head_AnimBp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMale_Medium_Galileo_Gondola_Head_AnimBp_C>();
	}
};
static_assert(alignof(UMale_Medium_Galileo_Gondola_Head_AnimBp_C) == 0x000010, "Wrong alignment on UMale_Medium_Galileo_Gondola_Head_AnimBp_C");
static_assert(sizeof(UMale_Medium_Galileo_Gondola_Head_AnimBp_C) == 0x000630, "Wrong size on UMale_Medium_Galileo_Gondola_Head_AnimBp_C");
static_assert(offsetof(UMale_Medium_Galileo_Gondola_Head_AnimBp_C, UberGraphFrame) == 0x0004B0, "Member 'UMale_Medium_Galileo_Gondola_Head_AnimBp_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UMale_Medium_Galileo_Gondola_Head_AnimBp_C, AnimBlueprintClassSubsystem_PropertyAccess) == 0x0004B8, "Member 'UMale_Medium_Galileo_Gondola_Head_AnimBp_C::AnimBlueprintClassSubsystem_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UMale_Medium_Galileo_Gondola_Head_AnimBp_C, AnimGraphNode_Root) == 0x0004C0, "Member 'UMale_Medium_Galileo_Gondola_Head_AnimBp_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UMale_Medium_Galileo_Gondola_Head_AnimBp_C, AnimGraphNode_CopyPoseFromMesh) == 0x0004F0, "Member 'UMale_Medium_Galileo_Gondola_Head_AnimBp_C::AnimGraphNode_CopyPoseFromMesh' has a wrong offset!");

}

