#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mansion_Outdoor_Umbrella_01_closed

#include "Basic.hpp"

#include "Parent_BuildingPropActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Mansion_Outdoor_Umbrella_01_closed.Mansion_Outdoor_Umbrella_01_closed_C
// 0x0000 (0x0C88 - 0x0C88)
class AMansion_Outdoor_Umbrella_01_closed_C final : public AParent_BuildingPropActor_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Mansion_Outdoor_Umbrella_01_closed_C">();
	}
	static class AMansion_Outdoor_Umbrella_01_closed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMansion_Outdoor_Umbrella_01_closed_C>();
	}
};
static_assert(alignof(AMansion_Outdoor_Umbrella_01_closed_C) == 0x000008, "Wrong alignment on AMansion_Outdoor_Umbrella_01_closed_C");
static_assert(sizeof(AMansion_Outdoor_Umbrella_01_closed_C) == 0x000C88, "Wrong size on AMansion_Outdoor_Umbrella_01_closed_C");

}

