#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NewLevelWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass NewLevelWidget.NewLevelWidget_C
// 0x0020 (0x0350 - 0x0330)
class UNewLevelWidget_C final : public UAthenaLevelUpWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0330(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       placementOffset;                                   // 0x0338(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class ULevelUpVisuals_C*                      LevelUpVisuals;                                    // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          IsPlaced;                                          // 0x0348(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_NewLevelWidget(int32 EntryPoint);
	void EventMoveforEoM(class FName Placement);
	void ShowLevelReward();
	void OutroFinished();
	void Construct();
	void ShowWidget(int32 NewLevel);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NewLevelWidget_C">();
	}
	static class UNewLevelWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNewLevelWidget_C>();
	}
};
static_assert(alignof(UNewLevelWidget_C) == 0x000008, "Wrong alignment on UNewLevelWidget_C");
static_assert(sizeof(UNewLevelWidget_C) == 0x000350, "Wrong size on UNewLevelWidget_C");
static_assert(offsetof(UNewLevelWidget_C, UberGraphFrame) == 0x000330, "Member 'UNewLevelWidget_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UNewLevelWidget_C, placementOffset) == 0x000338, "Member 'UNewLevelWidget_C::placementOffset' has a wrong offset!");
static_assert(offsetof(UNewLevelWidget_C, LevelUpVisuals) == 0x000340, "Member 'UNewLevelWidget_C::LevelUpVisuals' has a wrong offset!");
static_assert(offsetof(UNewLevelWidget_C, IsPlaced) == 0x000348, "Member 'UNewLevelWidget_C::IsPlaced' has a wrong offset!");

}

