#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Nightmare_Crashed_Helicopter

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Nightmare_Crashed_Helicopter.Nightmare_Crashed_Helicopter_C
// 0x0000 (0x0BA8 - 0x0BA8)
class ANightmare_Crashed_Helicopter_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Nightmare_Crashed_Helicopter_C">();
	}
	static class ANightmare_Crashed_Helicopter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANightmare_Crashed_Helicopter_C>();
	}
};
static_assert(alignof(ANightmare_Crashed_Helicopter_C) == 0x000008, "Wrong alignment on ANightmare_Crashed_Helicopter_C");
static_assert(sizeof(ANightmare_Crashed_Helicopter_C) == 0x000BA8, "Wrong size on ANightmare_Crashed_Helicopter_C");

}

