#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OodleHandlerComponent

#include "Basic.hpp"


namespace SDK
{

// Enum OodleHandlerComponent.EOodleEnableMode
// NumValues: 0x0002
enum class EOodleEnableMode : uint8
{
	AlwaysEnabled                            = 0,
	WhenCompressedPacketReceived             = 1,
};

}

