#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Pipe03

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Pipe03.Pipe03_C
// 0x0000 (0x0BA8 - 0x0BA8)
class APipe03_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Pipe03_C">();
	}
	static class APipe03_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APipe03_C>();
	}
};
static_assert(alignof(APipe03_C) == 0x000008, "Wrong alignment on APipe03_C");
static_assert(sizeof(APipe03_C) == 0x000BA8, "Wrong size on APipe03_C");

}

