#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_Apple_Tree

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Prop_Apple_Tree.Prop_Apple_Tree_C
// 0x0008 (0x0BB0 - 0x0BA8)
class AProp_Apple_Tree_C final : public ABuildingProp
{
public:
	class UBuildingActorCBGASpawnComponent_C*     BuildingActorCBGASpawnComponent;                   // 0x0BA8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Prop_Apple_Tree_C">();
	}
	static class AProp_Apple_Tree_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_Apple_Tree_C>();
	}
};
static_assert(alignof(AProp_Apple_Tree_C) == 0x000008, "Wrong alignment on AProp_Apple_Tree_C");
static_assert(sizeof(AProp_Apple_Tree_C) == 0x000BB0, "Wrong size on AProp_Apple_Tree_C");
static_assert(offsetof(AProp_Apple_Tree_C, BuildingActorCBGASpawnComponent) == 0x000BA8, "Member 'AProp_Apple_Tree_C::BuildingActorCBGASpawnComponent' has a wrong offset!");

}

