#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_BouncyUmbrella_C

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Prop_TirePile_01_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Prop_BouncyUmbrella_C.Prop_BouncyUmbrella_C_C
// 0x0010 (0x0C08 - 0x0BF8)
class AProp_BouncyUmbrella_C_C final : public AProp_TirePile_01_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Prop_BouncyUmbrella_C_C;            // 0x0BF8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UClass*                                 BounceGE;                                          // 0x0C00(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Prop_BouncyUmbrella_C(int32 EntryPoint);
	void BndEvt__Jump_Collision_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Prop_BouncyUmbrella_C_C">();
	}
	static class AProp_BouncyUmbrella_C_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_BouncyUmbrella_C_C>();
	}
};
static_assert(alignof(AProp_BouncyUmbrella_C_C) == 0x000008, "Wrong alignment on AProp_BouncyUmbrella_C_C");
static_assert(sizeof(AProp_BouncyUmbrella_C_C) == 0x000C08, "Wrong size on AProp_BouncyUmbrella_C_C");
static_assert(offsetof(AProp_BouncyUmbrella_C_C, UberGraphFrame_Prop_BouncyUmbrella_C_C) == 0x000BF8, "Member 'AProp_BouncyUmbrella_C_C::UberGraphFrame_Prop_BouncyUmbrella_C_C' has a wrong offset!");
static_assert(offsetof(AProp_BouncyUmbrella_C_C, BounceGE) == 0x000C00, "Member 'AProp_BouncyUmbrella_C_C::BounceGE' has a wrong offset!");

}

