#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuestNotification

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteUI_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass QuestNotification.QuestNotification_C
// 0x0108 (0x0450 - 0x0348)
class UQuestNotification_C final : public UFortNotificationEntry_Quest
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0348(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Outro;                                             // 0x0350(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Intro;                                             // 0x0358(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       ResetQuestComplete;                                // 0x0360(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       QuestComplete;                                     // 0x0368(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       FillProgress;                                      // 0x0370(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UBorder*                                Border_TimerContainer;                             // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          BorderXPBar;                                       // 0x0380(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Check;                                             // 0x0388(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          CommonBorder_0;                                    // 0x0390(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 GreenFill;                                         // 0x0398(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFortLazyImage*                         Icon_Mission;                                      // 0x03A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_glow;                                        // 0x03A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Spark;                                       // 0x03B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_textglow;                                    // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_textglow_2;                                  // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ImageArrow;                                        // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ImageTimer;                                        // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          Mission_Header;                                    // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ProgressFill;                                      // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ProgressFill_Current;                              // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_Missions;                                  // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   Text_AssistBlock;                                  // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_TimeRemainingUrgent;                          // 0x0400(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       TextMissionType;                                   // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_Complete;                           // 0x0410(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_Urgent;                             // 0x0418(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               MID_MissionHeader;                                 // 0x0420(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortRarity                                   ChallengeRarity;                                   // 0x0428(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_429[0x3];                                      // 0x0429(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           Rarity01_Default;                                  // 0x042C(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           Rarity02_Selected;                                 // 0x043C(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_QuestNotification(int32 EntryPoint);
	void OnFocusLost(const struct FFocusEvent& InFocusEvent);
	void BP_OnRaritySet(EFortRarity Rarity);
	void EventOnIntroStart();
	void EventOnStartComplete();
	void BP_OnTimerSet(EAthenaChallengeTimerState TimerState);
	void SetAssistData(bool bWasAssisted, const class FString& OtherPlayersName);
	void EventReset();
	void EventCompleteAnim();
	void EventFillComplete();
	void OnInitialized();
	void UpdateDefaultObjectiveVisuals();
	void UpdateQuestVisuals(const struct FFortChallengeSetStyle& DisplayStyle);
	void PreConstruct(bool IsDesignTime);
	void StartNotificationOutro();
	void StartNotificationIntro();
	void Construct();
	void UpdateProgress();
	void SetRarity();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"QuestNotification_C">();
	}
	static class UQuestNotification_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQuestNotification_C>();
	}
};
static_assert(alignof(UQuestNotification_C) == 0x000008, "Wrong alignment on UQuestNotification_C");
static_assert(sizeof(UQuestNotification_C) == 0x000450, "Wrong size on UQuestNotification_C");
static_assert(offsetof(UQuestNotification_C, UberGraphFrame) == 0x000348, "Member 'UQuestNotification_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, Outro) == 0x000350, "Member 'UQuestNotification_C::Outro' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, Intro) == 0x000358, "Member 'UQuestNotification_C::Intro' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, ResetQuestComplete) == 0x000360, "Member 'UQuestNotification_C::ResetQuestComplete' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, QuestComplete) == 0x000368, "Member 'UQuestNotification_C::QuestComplete' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, FillProgress) == 0x000370, "Member 'UQuestNotification_C::FillProgress' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, Border_TimerContainer) == 0x000378, "Member 'UQuestNotification_C::Border_TimerContainer' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, BorderXPBar) == 0x000380, "Member 'UQuestNotification_C::BorderXPBar' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, Check) == 0x000388, "Member 'UQuestNotification_C::Check' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, CommonBorder_0) == 0x000390, "Member 'UQuestNotification_C::CommonBorder_0' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, GreenFill) == 0x000398, "Member 'UQuestNotification_C::GreenFill' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, Icon_Mission) == 0x0003A0, "Member 'UQuestNotification_C::Icon_Mission' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, Image_glow) == 0x0003A8, "Member 'UQuestNotification_C::Image_glow' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, Image_Spark) == 0x0003B0, "Member 'UQuestNotification_C::Image_Spark' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, Image_textglow) == 0x0003B8, "Member 'UQuestNotification_C::Image_textglow' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, Image_textglow_2) == 0x0003C0, "Member 'UQuestNotification_C::Image_textglow_2' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, ImageArrow) == 0x0003C8, "Member 'UQuestNotification_C::ImageArrow' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, ImageTimer) == 0x0003D0, "Member 'UQuestNotification_C::ImageTimer' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, Mission_Header) == 0x0003D8, "Member 'UQuestNotification_C::Mission_Header' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, ProgressFill) == 0x0003E0, "Member 'UQuestNotification_C::ProgressFill' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, ProgressFill_Current) == 0x0003E8, "Member 'UQuestNotification_C::ProgressFill_Current' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, SizeBox_Missions) == 0x0003F0, "Member 'UQuestNotification_C::SizeBox_Missions' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, Text_AssistBlock) == 0x0003F8, "Member 'UQuestNotification_C::Text_AssistBlock' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, Text_TimeRemainingUrgent) == 0x000400, "Member 'UQuestNotification_C::Text_TimeRemainingUrgent' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, TextMissionType) == 0x000408, "Member 'UQuestNotification_C::TextMissionType' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, WidgetSwitcher_Complete) == 0x000410, "Member 'UQuestNotification_C::WidgetSwitcher_Complete' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, WidgetSwitcher_Urgent) == 0x000418, "Member 'UQuestNotification_C::WidgetSwitcher_Urgent' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, MID_MissionHeader) == 0x000420, "Member 'UQuestNotification_C::MID_MissionHeader' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, ChallengeRarity) == 0x000428, "Member 'UQuestNotification_C::ChallengeRarity' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, Rarity01_Default) == 0x00042C, "Member 'UQuestNotification_C::Rarity01_Default' has a wrong offset!");
static_assert(offsetof(UQuestNotification_C, Rarity02_Selected) == 0x00043C, "Member 'UQuestNotification_C::Rarity02_Selected' has a wrong offset!");

}

