#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Roof_Ducts04b

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Roof_Ducts04b.Roof_Ducts04b_C
// 0x0000 (0x0BA8 - 0x0BA8)
class ARoof_Ducts04b_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Roof_Ducts04b_C">();
	}
	static class ARoof_Ducts04b_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARoof_Ducts04b_C>();
	}
};
static_assert(alignof(ARoof_Ducts04b_C) == 0x000008, "Wrong alignment on ARoof_Ducts04b_C");
static_assert(sizeof(ARoof_Ducts04b_C) == 0x000BA8, "Wrong size on ARoof_Ducts04b_C");

}

