#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SM_Boardwalk_Stair34

#include "Basic.hpp"

#include "SM_Boardwalk_Stair34_classes.hpp"
#include "SM_Boardwalk_Stair34_parameters.hpp"


namespace SDK
{

// Function SM_Boardwalk_Stair34.SM_Boardwalk_Stair34_C.ExecuteUbergraph_SM_Boardwalk_Stair34
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ASM_Boardwalk_Stair34_C::ExecuteUbergraph_SM_Boardwalk_Stair34(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_SM_Boardwalk_Stair34");

	Params::SM_Boardwalk_Stair34_C_ExecuteUbergraph_SM_Boardwalk_Stair34 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SM_Boardwalk_Stair34.SM_Boardwalk_Stair34_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ASM_Boardwalk_Stair34_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

