#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tiered_Chest_Athena_FactionChest_NoLocks

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "Struct_FactionChest_FactionMapping_structs.hpp"
#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Tiered_Chest_Athena_FactionChest_NoLocks.Tiered_Chest_Athena_FactionChest_NoLocks_C
// 0x00E0 (0x0DE0 - 0x0D00)
class ATiered_Chest_Athena_FactionChest_NoLocks_C final : public ABuildingContainer
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0D00(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      P_NS_Faction_Chest_Idle;                           // 0x0D08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Faction_Crate_Glows;                               // 0x0D10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAthena_FactionSelection_Component_C*   Athena_FactionSelection_AlterEgo;                  // 0x0D18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Chest_Open_Sound;                                  // 0x0D20(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   TreasureLight;                                     // 0x0D28(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        Chest_Ambient_Sound;                               // 0x0D30(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0_Time_D8A1398E4AFA37BBDECCF293383ABE9F;  // 0x0D38(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_0__Direction_D8A1398E4AFA37BBDECCF293383ABE9F; // 0x0D3C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D3D[0x3];                                      // 0x0D3D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_0;                                        // 0x0D40(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MobileSelectedTL_LerpInteactoIcon_0AE82E2D4E1FCFD3E2E9F1BE946C1D69; // 0x0D48(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MobileSelectedTL_LerpObject_0AE82E2D4E1FCFD3E2E9F1BE946C1D69; // 0x0D4C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            MobileSelectedTL__Direction_0AE82E2D4E1FCFD3E2E9F1BE946C1D69; // 0x0D50(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D51[0x7];                                      // 0x0D51(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     MobileSelectedTL;                                  // 0x0D58(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MobileOnInteractTL_LERP_76E2C73945E36888260E65A4B339A848; // 0x0D60(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            MobileOnInteractTL__Direction_76E2C73945E36888260E65A4B339A848; // 0x0D64(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D65[0x3];                                      // 0x0D65(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     MobileOnInteractTL;                                // 0x0D68(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInstanceDynamic*>       MIDs;                                              // 0x0D70(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	float                                         MobileWiggleAmount;                                // 0x0D80(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ChestChimeVisualUpdate;                            // 0x0D84(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInterface*                     MobileInteractionMaterial;                         // 0x0D88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   MobileInteractIcon;                                // 0x0D90(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                MobileInteractIconLocation;                        // 0x0D98(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                MobileInteractIconScale;                           // 0x0DA4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         OpenFX_Rotation;                                   // 0x0DB0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           T_Faction;                                         // 0x0DB4(0x0008)(Edit, BlueprintVisible, Net, DisableEditOnInstance, RepNotify, NoDestructor, HasGetValueTypeHash)
	class FName                                   NeutralLootTier;                                   // 0x0DBC(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DC4[0x4];                                      // 0x0DC4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      Loot_Effect_Niagara;                               // 0x0DC8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FStruct_FactionChest_FactionMapping> Struct_FactionMapping;                             // 0x0DD0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void OnRep_T_Faction();
	void OnSetCustomDepthStencilValue(const TArray<class UPrimitiveComponent*>& PrimComponents, bool bUseCustomDepth, int32 StencilValue, bool* bOutConsume);
	void SetVisibleMobileInteractIcon(bool Visible);
	void GetMaxAudibleDistance(float* Max_Distance);
	void CleanupWiggleMIDs();
	void CreateMobileMIDs();
	bool ShouldDie(float Damage, class AController* EventInstigator, class AActor* DamageCauser);
	void SetLightVisibility(bool Visible);
	void UserConstructionScript();
	void MobileOnInteractTL__FinishedFunc();
	void MobileOnInteractTL__UpdateFunc();
	void MobileSelectedTL__FinishedFunc();
	void MobileSelectedTL__UpdateFunc();
	void Timeline_0__FinishedFunc();
	void Timeline_0__UpdateFunc();
	void OnReady_0169621A44481EDB77F98E9970DE4ED0(class AFortGameStateAthena* GameState, const class UFortPlaylist* Playlist, const struct FGameplayTagContainer& PlaylistContextTags);
	void OnLoot();
	void ReceiveBeginPlay();
	void ReceiveDestroyed();
	void OnSetSearched();
	void Mobile_Outline_On();
	void Mobile_Outline_Off();
	void Mobile_OnInteract();
	void Mobile_OnDisconnect();
	void EnableBacchusHighlight();
	void DisableBacchusHighlight();
	void OnBeginSearch();
	void OnDeathPlayEffects(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AFortPawn* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext);
	void BndEvt__Athena_FactionSelection_AlterEgo_K2Node_ComponentBoundEvent_0_OnFactionSelected__DelegateSignature(const struct FGameplayTag& FactionTagOut);
	void PlayOpeningTimeLine();
	void BlueprintOnInteract(const class AFortPawn* InteractingPawn, const EInteractionBeingAttempted InteractionBeingAttempted);
	void ExecuteUbergraph_Tiered_Chest_Athena_FactionChest_NoLocks(int32 EntryPoint);

	bool BlueprintCanInteract(const class AFortPawn* InteractingPawn, const EInteractionBeingAttempted InteractionBeingAttempted, const ETInteractionType InteractionType) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Tiered_Chest_Athena_FactionChest_NoLocks_C">();
	}
	static class ATiered_Chest_Athena_FactionChest_NoLocks_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATiered_Chest_Athena_FactionChest_NoLocks_C>();
	}
};
static_assert(alignof(ATiered_Chest_Athena_FactionChest_NoLocks_C) == 0x000008, "Wrong alignment on ATiered_Chest_Athena_FactionChest_NoLocks_C");
static_assert(sizeof(ATiered_Chest_Athena_FactionChest_NoLocks_C) == 0x000DE0, "Wrong size on ATiered_Chest_Athena_FactionChest_NoLocks_C");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, UberGraphFrame) == 0x000D00, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, P_NS_Faction_Chest_Idle) == 0x000D08, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::P_NS_Faction_Chest_Idle' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, Faction_Crate_Glows) == 0x000D10, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::Faction_Crate_Glows' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, Athena_FactionSelection_AlterEgo) == 0x000D18, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::Athena_FactionSelection_AlterEgo' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, Chest_Open_Sound) == 0x000D20, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::Chest_Open_Sound' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, TreasureLight) == 0x000D28, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::TreasureLight' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, Chest_Ambient_Sound) == 0x000D30, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::Chest_Ambient_Sound' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, Timeline_0_Time_D8A1398E4AFA37BBDECCF293383ABE9F) == 0x000D38, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::Timeline_0_Time_D8A1398E4AFA37BBDECCF293383ABE9F' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, Timeline_0__Direction_D8A1398E4AFA37BBDECCF293383ABE9F) == 0x000D3C, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::Timeline_0__Direction_D8A1398E4AFA37BBDECCF293383ABE9F' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, Timeline_0) == 0x000D40, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::Timeline_0' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, MobileSelectedTL_LerpInteactoIcon_0AE82E2D4E1FCFD3E2E9F1BE946C1D69) == 0x000D48, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::MobileSelectedTL_LerpInteactoIcon_0AE82E2D4E1FCFD3E2E9F1BE946C1D69' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, MobileSelectedTL_LerpObject_0AE82E2D4E1FCFD3E2E9F1BE946C1D69) == 0x000D4C, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::MobileSelectedTL_LerpObject_0AE82E2D4E1FCFD3E2E9F1BE946C1D69' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, MobileSelectedTL__Direction_0AE82E2D4E1FCFD3E2E9F1BE946C1D69) == 0x000D50, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::MobileSelectedTL__Direction_0AE82E2D4E1FCFD3E2E9F1BE946C1D69' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, MobileSelectedTL) == 0x000D58, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::MobileSelectedTL' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, MobileOnInteractTL_LERP_76E2C73945E36888260E65A4B339A848) == 0x000D60, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::MobileOnInteractTL_LERP_76E2C73945E36888260E65A4B339A848' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, MobileOnInteractTL__Direction_76E2C73945E36888260E65A4B339A848) == 0x000D64, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::MobileOnInteractTL__Direction_76E2C73945E36888260E65A4B339A848' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, MobileOnInteractTL) == 0x000D68, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::MobileOnInteractTL' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, MIDs) == 0x000D70, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::MIDs' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, MobileWiggleAmount) == 0x000D80, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::MobileWiggleAmount' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, ChestChimeVisualUpdate) == 0x000D84, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::ChestChimeVisualUpdate' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, MobileInteractionMaterial) == 0x000D88, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::MobileInteractionMaterial' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, MobileInteractIcon) == 0x000D90, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::MobileInteractIcon' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, MobileInteractIconLocation) == 0x000D98, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::MobileInteractIconLocation' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, MobileInteractIconScale) == 0x000DA4, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::MobileInteractIconScale' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, OpenFX_Rotation) == 0x000DB0, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::OpenFX_Rotation' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, T_Faction) == 0x000DB4, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::T_Faction' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, NeutralLootTier) == 0x000DBC, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::NeutralLootTier' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, Loot_Effect_Niagara) == 0x000DC8, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::Loot_Effect_Niagara' has a wrong offset!");
static_assert(offsetof(ATiered_Chest_Athena_FactionChest_NoLocks_C, Struct_FactionMapping) == 0x000DD0, "Member 'ATiered_Chest_Athena_FactionChest_NoLocks_C::Struct_FactionMapping' has a wrong offset!");

}

