#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseFortnite_Player_PlayerStartComponent

#include "Basic.hpp"

#include "VerseFortnite_Player_PlayerStartComponent_classes.hpp"
#include "VerseFortnite_Player_PlayerStartComponent_parameters.hpp"


namespace SDK
{

// Function VerseFortnite_Player_PlayerStartComponent.PlayerStartComponent.findAllInPlayspaceWithTags
// (Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UObject*                          __verse_0x9866B8E7_contextObject                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class FString>                   __verse_0xC3624B24_searchTags                          (Parm, HasGetValueTypeHash)
// TArray<class UPlayerStartComponent*>    RetVal                                                 (Parm, OutParm, ReturnParm, HasGetValueTypeHash)

TArray<class UPlayerStartComponent*> UPlayerStartComponent::findAllInPlayspaceWithTags(class UObject* __verse_0x9866B8E7_contextObject, const TArray<class FString>& __verse_0xC3624B24_searchTags)
{
	static class UFunction* Func = nullptr;
	class UClass* StaticClss = StaticClass();

	if (Func == nullptr)
		Func = StaticClss->FindFunction("findAllInPlayspaceWithTags");

	Params::PlayerStartComponent_findAllInPlayspaceWithTags Parms{};

	Parms.__verse_0x9866B8E7_contextObject = __verse_0x9866B8E7_contextObject;
	Parms.__verse_0xC3624B24_searchTags = std::move(__verse_0xC3624B24_searchTags);

	StaticClss->DefaultObject->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function VerseFortnite_Player_PlayerStartComponent.PlayerStartComponent.$InitCDO
// ()

void UPlayerStartComponent::_InitCDO()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitCDO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseFortnite_Player_PlayerStartComponent.PlayerStartComponent.$InitInstance
// ()

void UPlayerStartComponent::_InitInstance()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("$InitInstance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VerseFortnite_Player_PlayerStartComponent.PlayerStartComponent.addTags
// (Native, Public, BlueprintCallable)
// Parameters:
// TArray<class FString>                   __verse_0xE77537C1_newTags                             (Parm, HasGetValueTypeHash)

void UPlayerStartComponent::addTags(const TArray<class FString>& __verse_0xE77537C1_newTags)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("addTags");

	Params::PlayerStartComponent_addTags Parms{};

	Parms.__verse_0xE77537C1_newTags = std::move(__verse_0xE77537C1_newTags);

	UObject::ProcessEvent(Func, &Parms);
}


// Function VerseFortnite_Player_PlayerStartComponent.PlayerStartComponent.GetPosition
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class UVector3*                         RetVal                                                 (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UVector3* UPlayerStartComponent::GetPosition()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetPosition");

	Params::PlayerStartComponent_GetPosition Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

