#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Viking_Ship_Hull_A2

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Viking_Ship_Hull_A2.Viking_Ship_Hull_A2_C
// 0x0000 (0x0AC8 - 0x0AC8)
class AViking_Ship_Hull_A2_C final : public ABuildingRoof
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Viking_Ship_Hull_A2_C">();
	}
	static class AViking_Ship_Hull_A2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AViking_Ship_Hull_A2_C>();
	}
};
static_assert(alignof(AViking_Ship_Hull_A2_C) == 0x000008, "Wrong alignment on AViking_Ship_Hull_A2_C");
static_assert(sizeof(AViking_Ship_Hull_A2_C) == 0x000AC8, "Wrong size on AViking_Ship_Hull_A2_C");

}

