#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Viking_Ship_Mast

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Viking_Ship_Mast.Viking_Ship_Mast_C
// 0x0000 (0x0BA8 - 0x0BA8)
class AViking_Ship_Mast_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Viking_Ship_Mast_C">();
	}
	static class AViking_Ship_Mast_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AViking_Ship_Mast_C>();
	}
};
static_assert(alignof(AViking_Ship_Mast_C) == 0x000008, "Wrong alignment on AViking_Ship_Mast_C");
static_assert(sizeof(AViking_Ship_Mast_C) == 0x000BA8, "Wrong size on AViking_Ship_Mast_C");

}

